window.PROMPT_DATA={
  "updated": "2026-06-30",
  "note": "x.com에서 수집한 GPT-image2 트렌드 프롬프트 라이브러리. Krea2로 재현 테스트. 새 링크는 prompts 배열에 append 후 generate_all.py 실행 → index.html 자동 반영.",
  "prompts": [
    {
      "id": "xxd-1",
      "source": "https://x.com/xiaoxiaodong01/status/2071554295271391317",
      "author": "@xiaoxiaodong01",
      "date": "2026-06-29",
      "lang": "zh",
      "target_model": "GPT-image2",
      "category": "이벤트 포스터",
      "title": "절제·장중 현장감 — 거대 단절 타이틀이 주제를 관통",
      "prompt": "围绕任意主题对象生成一张克制、庄重、具有现场感的视觉海报：主题对象以近距离正面主形体占据画面中心，姿态稳定、目光或核心朝向略带停顿感，背景保持大面积安静留白与细微真实纹理，底部用一条自然承托面或信息基线压住重心。最强视觉动作是让超大标题字标横向穿过主题对象的中段，字形使用厚重几何无衬线并做断裂、切割、留空处理，形成被主体遮挡又反过来压住主体的图像文字张力；标题之上可有一行极小的轻细说明文字，标题内部或其轴线上嵌入拉宽字距的副标题，旁侧放少量主题派生文字，底部再以紧密小字号排出时间、地点、署名或参数信息，整体阅读顺序先看主体气场，再被巨大断裂字吸住，最后落到底部信息。色彩从主题自身的材质、情绪与场景语义中提取，保留大面积低饱和中性底场、较深的主体结构色、清晰高明度信息文字和少量冷静强调色的角色关系；明度层次干净，饱和度受控，背景偏清透安静，阴影有厚度但不浑浊，使画面呈现冷静、精确、带仪式感的专业质感。画面边缘留出克制空白，顶部角落可放极小印章式标识，整体避免热闹装饰和插画化，摄影质感真实，字体排版大胆而不喧闹，所有文字与主体发生空间遮挡和层级关系。\n\n——————\n画面主题: 中年钢琴家近景肖像海报，保持安静灰墙和桌面承托感\n演出发布用: 用作钢琴独奏会主视觉和社交平台预告图\n保留文字: 巨大断裂标题写「SOLO」，副标题放钢琴家姓名和日期地点\n尺寸: 竖版 9:10",
      "ref_image": "https://pbs.twimg.com/media/HL-isawaAAApuTz.jpg",
      "result": "results/xxd-1.png",
      "seed": 2142395245,
      "prompt_ko": "임의의 주제 대상으로 절제되고 장중하며 현장감 있는 비주얼 포스터를 생성한다. 주제 대상은 근거리 정면 주형체로 화면 중앙을 차지하고, 자세는 안정적이며 시선이나 핵심 방향에 약간의 멈춤감을 준다. 배경은 넓은 면적의 고요한 여백과 미세한 실제 질감을 유지하고, 하단은 자연스러운 받침면 또는 정보 기준선으로 무게중심을 눌러준다. [가장 강한 시각 동작] 초대형 타이틀 글자가 주제 대상의 중단을 가로로 관통하게 한다 — 자형은 두껍고 기하학적인 산세리프를 쓰되 단절·절단·여백 처리를 해서, 주체에 가려지면서도 거꾸로 주체를 눌러주는 이미지-텍스트 긴장감을 만든다. 타이틀 위에는 극히 작고 가는 설명 한 줄, 타이틀 내부나 그 축선상에 자간을 넓힌 부제를 끼워넣고, 옆에는 주제 파생 텍스트를 소량, 하단에는 촘촘한 작은 글씨로 시간·장소·서명·파라미터 정보를 배열한다. 읽기 순서: 주체의 기세 → 거대한 단절 글자에 시선이 붙들림 → 하단 정보. [색상] 주제 자체의 재질·정서·장면 의미에서 추출하되 넓은 저채도 중성 바탕 / 다소 짙은 주체 구조색 / 선명한 고명도 정보 텍스트 / 소량의 차분한 강조색 관계를 유지. 명도 계층은 깨끗, 채도는 절제, 배경은 맑고 고요, 그림자는 두께는 있되 탁하지 않게 → 차분·정밀·의식적인 프로페셔널 질감. 가장자리엔 절제된 여백, 상단 모서리엔 극소형 인장식 마크. 떠들썩한 장식·일러스트화를 피하고 사진 질감은 사실적으로, 타이포는 대담하되 시끄럽지 않게, 모든 텍스트가 주체와 공간적 가림·계층 관계를 갖게 한다.\n——————\n화면 주제: 중년 피아니스트 근경 초상 포스터, 고요한 회색 벽과 책상 받침감 유지\n공연 발표용: 피아노 독주회 메인 비주얼 및 SNS 예고 이미지\n유지 텍스트: 거대한 단절 타이틀에 「SOLO」, 부제에 피아니스트 이름·날짜·장소\n사이즈: 세로 9:10",
      "gen_prompt": "Restrained, dignified event poster. Close-up frontal portrait of a middle-aged pianist as the central main form, stable pose, quiet grey wall and desk support, large calm negative space, subtle real texture. STRONGEST ACTION: an oversized thick geometric sans-serif ENGLISH title 'SOLO' runs horizontally through the middle of the figure with break/cut/gap treatment, occluded by yet pressing on the subject. Tiny thin English caption line above; letter-spaced English subtitle (pianist name) on its axis; small English date/place/credit at the bottom. Low-saturation neutral ground, deep structural color, clear high-brightness text, minimal calm accent. Clean values, ceremonial professional photographic texture, tiny seal-like mark in a top corner. Bold but quiet typography, all text in clean legible English. Vertical 9:10."
    },
    {
      "id": "xxd-2",
      "source": "https://x.com/xiaoxiaodong01/status/2071554295271391317",
      "author": "@xiaoxiaodong01",
      "date": "2026-06-29",
      "lang": "zh",
      "target_model": "GPT-image2",
      "category": "이벤트 포스터",
      "title": "고식별 정보 비주얼 — 원형 윈도우 2개 + 측정감 기하",
      "prompt": "围绕任意主题对象生成一张高识别度信息视觉：用大面积明亮洁净的主题派生底色建立第一眼冲击，底色占据画面绝大多数面积，并被一个巨大的裁切圆弧或圆形色块推向边缘，形成强烈的图形压力和明确留白。核心主题影像不直接铺满，而以冷静单色化、网点半调或细密颗粒的方式嵌入两个不同尺度的圆形窗口，主窗口承载最重要人物、产品、符号或概念载体，次窗口作为节奏回声与叙事补充，两个圆之间可局部重叠或被边缘裁切。文字采用粗重、紧凑、块面感强的无衬线中文标题，形成左侧或主阅读区的大体量黑色信息块，次级信息用较小字号分层排列，顶部用黑色标签与浅色信息框建立课程卡片般的秩序感。加入少量精密几何装饰：标尺刻度、点阵、虚线斜向连接、短横强调条、线框小图标，让画面有探索、测量和界面化的理性气质，但装饰必须服务阅读路径。色彩从主题自身的材质、情绪和语义中提取，保留高明度大底色、深色结构文字、低饱和单色影像、极少量高饱和强调色的角色关系，整体明亮轻快、干净锋利、对比清晰；强调色只用于小面积信号点，避免平均分布。画面完成感应像一张大胆的设计课程或创新议题视觉，信息密度高但层级明确，圆形影像、粗黑标题、测量感几何与明亮底色共同构成记忆点。\n\n——————\n想替换成：产品设计创新讲座，重点呈现一位视觉设计讲师和一个产品经理嘉宾\n使用位置：线下沙龙报名页首图，也适合做社群转发卡片\n文字要求：标题突出“探索产品创新之路”，辅以时间、地点和两条议程\n尺寸选择：竖版 3:4",
      "ref_image": "https://pbs.twimg.com/media/HL-iyb6asAAxbDI.jpg",
      "result": "results/xxd-2.png",
      "seed": 1905967059,
      "prompt_ko": "임의의 주제 대상으로 식별성 높은 정보형 비주얼을 생성한다. 넓고 밝고 깨끗한 주제 파생 바탕색으로 첫인상 임팩트를 만들고, 바탕색이 화면 대부분을 차지하며 거대한 잘린 원호 또는 원형 색면이 가장자리로 밀어내 강한 그래픽 압력과 명확한 여백을 형성한다. 핵심 주제 이미지는 화면을 직접 채우지 않고 차분한 단색화·하프톤 망점·미세 입자 방식으로 크기가 다른 두 원형 창에 끼워넣는다. 주 창은 가장 중요한 인물·제품·심볼·개념을, 보조 창은 리듬의 메아리이자 서사 보충으로 쓰며 두 원은 부분적으로 겹치거나 가장자리에 잘릴 수 있다. [텍스트] 두껍고 촘촘하며 면적감 강한 산세리프 타이틀로 좌측 또는 주 가독 영역에 큰 검정 정보 블록을 형성, 하위 정보는 작은 글씨로 계층 배열, 상단엔 검정 라벨과 옅은 정보 박스로 강의 카드 같은 질서감. [장식] 눈금자 스케일·점 배열·점선 사선 연결·짧은 강조 바·라인 아이콘 등 정밀 기하 소량으로 탐구·측정·인터페이스적 이성 기질을 주되 반드시 읽기 동선에 복무. [색상] 고명도 큰 바탕 / 짙은 구조 텍스트 / 저채도 단색 이미지 / 극소량 고채도 강조색 관계. 전체는 밝고 경쾌·깨끗·날카롭고 대비 선명, 강조색은 작은 신호점에만(고른 분포 금지). 대담한 디자인 강좌/혁신 의제 비주얼처럼 정보 밀도는 높되 계층은 명확하게.\n——————\n바꾸고 싶은 것: 제품 디자인 혁신 강연, 비주얼 디자인 강사 1명 + 제품 매니저 게스트 1명 강조\n사용 위치: 오프라인 살롱 신청 페이지 헤더, 커뮤니티 전파 카드로도 적합\n텍스트 요구: 타이틀 \"探索产品创新之路(제품 혁신의 길을 탐구하다)\" 강조, 시간·장소 + 어젠다 2줄 보조\n사이즈: 세로 3:4",
      "gen_prompt": "High-recognition informational event poster. A large, bright, clean background color fills most of the frame, pushed by a giant cropped arc / circle block toward the edge for strong graphic pressure and clear negative space. Core subjects (a visual-design lecturer and a product-manager guest) embedded as cool monochrome / halftone imagery into two different-sized circular windows, partially overlapping. Bold tight blocky ENGLISH sans-serif title 'EXPLORE PRODUCT INNOVATION' as a large dark info block on the left / main reading area; secondary info layered in smaller size; a dark label and light info box at top for course-card order. Precise geometric decor: ruler ticks, dot matrix, dashed diagonal links, short emphasis bars, line icons, serving the reading path. Bright, crisp, high-contrast; accent only on small signal points. All text in clean legible English. Vertical 3:4."
    },
    {
      "id": "xxd-3",
      "source": "https://x.com/xiaoxiaodong01/status/2071554295271391317",
      "author": "@xiaoxiaodong01",
      "date": "2026-06-29",
      "lang": "zh",
      "target_model": "GPT-image2",
      "category": "이벤트 포스터",
      "title": "인용구 라인프레임 — 반투명 텍스트층 + 말풍선 꺾임",
      "prompt": "围绕任意主题对象生成一张冷静、庄重、信息感强的图文视觉：主题主形体以近距离大尺度占据画面中央，带有高反差、低彩度的纪实影像质感，边缘被干净裁切并与背后的明亮留白区域形成强烈的前后关系；外层用大面积主题派生的深色结构场承托画面，使主体像从安静的暗场中被推出。用一条极细的浅色线框在主体周围形成开放式引语容器，线框既包住主体又留出呼吸边界，其中一角可转化为对话气泡式折角或指向性转折，制造“话语被框住但仍向外延伸”的记忆点。文字是画面结构的一部分：核心短句放在主体下半部附近的半透明暗色信息层上，字号中等、行距紧、左对齐，形成克制的停顿；主题名称或主标题用粗重无衬线字放在下方视觉重心处，清晰、有分量、留足字间空气；可加入一个小而醒目的引号符号块作为节奏锚点。色彩从主题自身的材质、情绪和文化信号中提取，保留大面积深色结构场、中央干净高明度留白、低饱和主体影像、少量浅色信息线条与文字的角色关系，整体保持冷静精确、明暗清晰、边界洁净，深色必须通透不浑浊，浅色区域明亮而不刺眼。背景不做复杂场景，只服务于层次、权威感和阅读路径；质感可有细微影像颗粒与透明叠层，但不能削弱线框、文字和主体之间的清晰秩序。\n\n——————\n想替换成: 一位企业创始人或演讲者的正面肖像，气质冷静克制\n用在这里: 课程预告、公众号封面或朋友圈观点卡\n必须保留: 开放式引语线框、半透明文字层、人物主标题，尺寸 竖版 9:16",
      "ref_image": "https://pbs.twimg.com/media/HL-i5kDboAAt9mh.jpg",
      "result": "results/xxd-3.png",
      "seed": 1704654681,
      "prompt_ko": "임의의 주제 대상으로 차분·장중하고 정보감 강한 이미지+텍스트 비주얼을 생성한다. 주제 주형체가 근거리 대형 스케일로 화면 중앙을 차지하며 고대비·저채도의 다큐멘터리적 영상 질감을 띠고, 가장자리는 깔끔히 잘려 뒤의 밝은 여백과 강한 전후 관계를 이룬다. 외곽은 넓은 주제 파생 짙은색 구조장으로 화면을 받쳐 주체가 고요한 어두운 장에서 밀려나온 듯하게 한다. [핵심] 극히 가는 옅은색 라인 프레임으로 주체 둘레에 개방형 인용구 컨테이너를 만들되, 프레임은 주체를 감싸면서도 호흡 여백을 남기고 한쪽 모서리는 말풍선식 꺾임/지향성 전환으로 바꿔 '말이 틀에 갇혔지만 밖으로 뻗는' 기억점을 만든다. [텍스트=구조의 일부] 핵심 짧은 문구는 주체 하반부의 반투명 어두운 정보층 위에 중간 크기·좁은 행간·좌측 정렬로 절제된 멈춤을, 주제명/메인 타이틀은 두꺼운 산세리프로 하단 시각 무게중심에 선명·묵직하게 자간 여백 충분히. 작지만 눈에 띄는 따옴표 심볼 블록을 리듬 앵커로 추가 가능. [색상] 넓은 짙은 구조장 / 중앙의 깨끗한 고명도 여백 / 저채도 주체 이미지 / 소량 옅은 정보 라인·텍스트 관계. 차분·정밀, 명암 선명·경계 깔끔, 짙은색은 투명감 있게(탁하지 않게), 옅은 영역은 밝되 눈부시지 않게. 배경은 복잡한 장면 없이 계층·권위감·읽기 동선에만 복무, 미세 영상 입자·투명 오버레이는 가능하되 라인프레임·텍스트·주체 간 질서를 약화시키지 말 것.\n——————\n바꾸고 싶은 것: 기업 창업자/강연자의 정면 초상, 차분하고 절제된 기질\n사용처: 강좌 예고, 공식계정 커버, SNS 관점 카드\n반드시 유지: 개방형 인용구 라인프레임, 반투명 텍스트층, 인물 메인 타이틀 / 사이즈 세로 9:16",
      "gen_prompt": "Calm, dignified quote-style poster. Close-up large-scale frontal portrait of a corporate founder / speaker, high-contrast low-saturation documentary texture, clean-cut edges against a bright negative-space area; an outer large dark structural field pushes the subject out of a quiet dark stage. A very thin light line-frame forms an open quote container around the subject, with one corner turning into a speech-bubble fold. A core short ENGLISH phrase sits on a semi-transparent dark info layer in the lower half, medium size, tight leading, left-aligned; a bold sans-serif ENGLISH main title (the person's name) at the lower visual center; a small bold quotation-mark block as a rhythm anchor. Large dark field, clean central high-brightness space, low-saturation subject, minimal light info lines. Calm and precise, clear contrast, clean edges. All text in clean legible English. Vertical 9:16."
    },
    {
      "id": "xxd-4",
      "source": "https://x.com/xiaoxiaodong01/status/2071554295271391317",
      "author": "@xiaoxiaodong01",
      "date": "2026-06-29",
      "lang": "zh",
      "target_model": "GPT-image2",
      "category": "이벤트 포스터",
      "title": "듀얼 포커스 윈도우 — 세로 중축 텍스트로 연결",
      "prompt": "围绕任意主题对象生成一张清透、秩序感强的信息视觉：画面先读到中央两块高挑圆角色面，它们像被裁开的窗口，各自承载一个主题核心焦点，焦点可以从主题的人物、产品、符号或材料形态中提炼，采用近距离裁切与边缘露出的方式形成双焦点对话；两块窗口左右错位、大小接近但姿态不同，中间保留窄而安静的留白轴，放置少量细长竖排文字或短语，让信息像书脊一样把两个焦点连接起来。背景保持大面积明亮高键底色，加入极淡、低对比的重复几何纹理，纹理只提供文化感、秩序感和轻微纸面层次，不抢主体。标题区使用厚重、宽扁、紧密排列的粗体字，成为下方最强视觉重量，标题上方用中等字号建立活动或主题说明，标题下方用细条形信息带收纳副标题、时间、地点或补充说明，底部再以浅色信息栏承接次级资料，使阅读路径从双焦点到主标题再到细节。色彩从主题自身的材质、情绪和文化信号中提取，保留大面积明亮干净底色、少量饱和且边界清晰的强调色面、深色文字骨架和浅色信息托底的角色关系；整体应保持清透安静、明亮洁净、对比明确，强调色只集中在焦点窗口和关键信息处，避免脏灰、复古泛黄或过度装饰。成品应像克制的公共文化活动视觉，留白充足、层级精确、图像与文字互相嵌合，而不是普通拼贴或拥挤宣传单。\n\n——————\n活动方向: 人文讲座或影人对谈海报，保留双人物窗口和中轴竖排短语\n发布场景: 校园公众号、文化馆活动预告和现场导视都能直接使用\n文字内容: 主标题写“人文讲座”，下方放时间、地点、嘉宾姓名\n画幅尺寸: 竖版 9:10",
      "ref_image": "https://pbs.twimg.com/media/HL-jAAPbQAAPsYj.jpg",
      "result": "results/xxd-4.png",
      "seed": 1175676198,
      "prompt_ko": "임의의 주제 대상으로 맑고 질서감 강한 정보 비주얼을 생성한다. 화면에서 먼저 중앙의 길쭉한 둥근 모서리 색면 두 덩어리가 읽히고, 잘려 열린 창처럼 각각 하나의 주제 핵심 초점을 담는다. 초점은 주제의 인물·제품·심볼·재료 형태에서 추출하며 근거리 크롭과 가장자리 노출로 이중 초점 대화를 형성한다. 두 창은 좌우로 어긋나고 크기는 비슷하되 자세가 다르며, 가운데에 좁고 고요한 여백 축을 남겨 가늘고 긴 세로 텍스트/짧은 문구를 두어 정보가 책등처럼 두 초점을 잇게 한다. 배경은 넓은 밝은 하이키 바탕색을 유지하고 극히 옅고 저대비의 반복 기하 텍스처로 문화감·질서감·미세한 종이 질감만 제공(주체를 빼앗지 않음). [타이틀] 두껍고 넓적하며 촘촘히 배열된 볼드체로 하단 최강 시각 무게가 되고, 위엔 중간 크기로 행사·주제 설명, 아래엔 가는 띠 정보바로 부제·시간·장소, 맨 아래엔 옅은 정보란으로 하위 자료 → 읽기 동선 이중 초점→메인 타이틀→디테일. [색상] 넓은 밝고 깨끗한 바탕 / 소량의 채도 높고 경계 선명한 강조 색면 / 짙은 텍스트 골격 / 옅은 정보 받침 관계. 맑고 고요·밝고 깨끗·대비 명확, 강조색은 초점 창과 핵심 정보에만, 탁한 회색·복고풍 누런빛·과도한 장식 금지. 완성물은 절제된 공공 문화행사 비주얼처럼 여백 충분·계층 정밀·이미지와 텍스트가 맞물려야 하며 평범한 콜라주나 빽빽한 전단지가 아니어야 한다.\n——————\n행사 방향: 인문 강좌/영화인 대담 포스터, 2인 인물 창 + 중축 세로 문구 유지\n발행 장면: 캠퍼스 공식계정, 문화관 행사 예고, 현장 안내까지 바로 사용\n텍스트 내용: 메인 타이틀 \"人文讲座(인문 강좌)\", 아래에 시간·장소·게스트 이름\n화폭 사이즈: 세로 9:10",
      "gen_prompt": "Clean, orderly cultural-event poster. Two tall rounded-rectangle color panels read first at the center like cut-open windows, each holding one core focus (two speakers' portraits), close-cropped with edge reveal forming a dual-focus dialogue; left-right offset, similar size but different pose, with a narrow quiet whitespace axis between them holding slim vertical ENGLISH text connecting them like a spine. Bright high-key background with very faint low-contrast repeating geometric texture (culture / order / paper feel). A heavy, wide, tightly-set bold ENGLISH title 'HUMANITIES LECTURE' as the strongest bottom weight; a medium English event note above; a thin info strip below with subtitle / time / place; a light info bar at the very bottom. Bright clean high-contrast, accent only at the focus windows and key info. All text in clean legible English. Vertical 9:10."
    },
    {
      "id": "shz-1",
      "source": "https://x.com/sha_zdiii/status/2071262398561050680",
      "author": "@sha_zdiii",
      "date": "2026-06-28",
      "lang": "en",
      "target_model": "GPT-image2",
      "category": "제품 광고",
      "title": "여름 음료 광고 — 스플래시 + 바이럴 인스타 광고풍",
      "prompt": "(Ultra-realistic summer beverage commercial poster), stylish young woman wearing (soft pastel scarf wrapped around head) and (white luxury sunglasses), drinking from a (pink premium tropical can) with water splashing naturally around lips and chin, same fashion aesthetic, same scarf model look, bright blue sky background, tropical palm leaves, fresh watermelon slices at bottom, ice cubes in foreground, (premium product branding centered), bold energetic typography in background saying (Hydrate your Happy), vibrant summer color palette, glossy skin texture, golden sunlight, refreshing drink ad campaign, (cinematic lighting), (viral Instagram commercial style), high-end beverage photography, hyper-detailed, photorealistic, ultra-sharp focus, (8K HDR), luxury editorial ad, realistic splash physics, trendy youth marketing aesthetic.",
      "ref_image": "https://pbs.twimg.com/media/HL6aKVTbYAAURbP.jpg",
      "result": "results/shz-1.png",
      "seed": 101500771,
      "prompt_ko": "(초사실적 여름 음료 광고 포스터), 세련된 젊은 여성이 (머리에 부드러운 파스텔 스카프를 두르고) (흰색 럭셔리 선글라스)를 착용한 채 (핑크색 프리미엄 트로피컬 캔)으로 음료를 마시며 입술·턱 주변에 물이 자연스럽게 튀고, 동일한 패션 미학·동일한 스카프 모델룩, 밝은 파란 하늘 배경, 열대 야자수 잎, 하단에 신선한 수박 조각, 전경에 얼음 큐브, (프리미엄 제품 브랜딩 중앙 배치), 배경에 굵고 에너지 넘치는 타이포로 (Hydrate your Happy), 생기 있는 여름 색팔레트, 윤기 나는 피부 질감, 황금빛 햇살, 청량한 음료 광고 캠페인, (시네마틱 조명), (바이럴 인스타그램 광고 스타일), 하이엔드 음료 사진, 초디테일, 포토리얼, 초선명 포커스, (8K HDR), 럭셔리 에디토리얼 광고, 사실적인 물 튀김 물리, 트렌디한 청년 마케팅 미학."
    },
    {
      "id": "ai-synthia-1",
      "source": "https://x.com/AIwithSynthia/status/2071569612375048564",
      "author": "@AIwithSynthia",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "Gemini Nano Banana",
      "category": "콜라주/9패널",
      "title": "동일 인물 9컷 콜라주 — 손그림 두들 + 라이프스타일",
      "prompt": "A professional 3x3 collage featuring the same beautiful young woman photographed from the reference image with normal hair and eyeglasses from a top-down perspective on a soft white textured blanket. The woman appears in nine different creative scenes. Each panel contains hand-drawn black doodle illustrations interacting with her pose. Bright natural lighting, clean white background, high-end lifestyle photography, ultra-sharp details, magazine-quality composition, playful storytelling, realistic human proportions, consistent facial features across all nine panels.\nPanel 1 (Athlete): sporty white crop top, black athletic shorts, running shoes; mid-jump leaping over a hand-drawn hurdle; dynamic energetic pose.\nPanel 2 (Circus Performer): red circus outfit with gold accents; balancing on one foot atop a hand-drawn drum, both hands raised; cheerful confident smile.\nPanel 3 (Ice Cream Lover): pastel pink summer dress, white sneakers; sitting between two hand-drawn cafe chairs holding a large doodle ice cream cone; cute playful expression.\nPanel 4 (Superhero): superhero costume with flowing cape and boots; both fists raised to the sky; large hand-drawn cape extension; heroic expression.\nPanel 5 (Vacation Mode): tropical floral dress, sandals; relaxing on a hand-drawn beach towel, hands behind head; sunscreen and flip-flop doodles nearby.\nPanel 6 (Gym Struggle): fitted gym outfit with leggings; giant doodle barbell beside her; exaggerated struggling funny face.\nPanel 7 (Gymnast): gymnastics leotard; hanging between two hand-drawn rings; focused athletic graceful pose.\nPanel 8 (Shopping Queen): blazer, skirt, heels; holding two shopping bags labeled \"Shopping Day\"; happy confident luxury mood.\nPanel 9 (Rock Star): black leather jacket, ripped jeans, boots, bracelets, bandana; hand-drawn electric guitar across body; arms spread wide rockstar pose.\nOverall style: minimalist white aesthetic, hand-drawn black doodle illustrations, whimsical storytelling, clean flat-lay composition, Instagram viral trend, professional studio photography, ultra-realistic young woman, high detail, 8K quality, consistent appearance across all panels, bright soft lighting, modern lifestyle editorial.",
      "prompt_ko": "레퍼런스 이미지의 동일한 젊은 여성(보통 머리, 안경)을 부드러운 흰색 질감 담요 위에서 탑다운 시점으로 촬영한 프로페셔널 3x3 콜라주. 여성이 9개의 서로 다른 창의적 장면에 등장하며, 각 패널엔 그녀의 포즈와 상호작용하는 손그림 검정 두들 일러스트. 밝은 자연광, 깨끗한 흰 배경, 하이엔드 라이프스타일 사진, 초선명 디테일, 잡지급 구성, 9패널 전체 동일한 얼굴.\n패널1(운동선수): 스포티 흰 크롭탑+검정 반바지+러닝화, 손그림 허들 넘는 점프 순간.\n패널2(서커스): 금장식 빨강 의상, 손그림 드럼 위 한 발 균형, 자신감 미소.\n패널3(아이스크림): 파스텔 핑크 원피스+흰 스니커즈, 손그림 카페 의자 사이, 거대 두들 아이스크림콘.\n패널4(슈퍼히어로): 망토 히어로 의상, 양주먹 하늘로, 뒤에 큰 손그림 망토.\n패널5(휴가): 열대 플로럴 원피스, 손그림 비치타올에 누움, 선크림·플립플롭 두들.\n패널6(헬스 고통): 핏한 짐복+레깅스, 거대 두들 바벨, 과장된 고통 표정(유머).\n패널7(체조): 레오타드, 손그림 링 2개 사이 매달림, 집중 표정.\n패널8(쇼핑여왕): 블레이저+스커트+힐, \"Shopping Day\" 쇼핑백 2개, 럭셔리 무드.\n패널9(록스타): 검정 가죽재킷+찢청+부츠+밴다나, 손그림 일렉기타, 팔 벌린 포즈.\n전체: 미니멀 화이트 미학, 손그림 검정 두들, 깔끔한 플랫레이, 인스타 바이럴, 초사실적 여성, 8K, 전 패널 동일 외모.\n※ 레퍼런스 이미지 기반(i2i) — Krea2는 t2i라 인물 일관성 없이 콜라주 구조만 재현됨.",
      "ref_image": "https://pbs.twimg.com/media/HL-xlEZbIAAzoY_.jpg",
      "result": "results/ai-synthia-1.png",
      "seed": 814467328
    },
    {
      "id": "lucia-1",
      "source": "https://x.com/luciaverseai/status/2071404468143620385",
      "author": "@luciaverseai",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT-image2",
      "category": "브랜딩 목업",
      "title": "브랜드 아이덴티티 플랫레이 목업",
      "prompt": "Create a premium flat-lay, top-down branding and packaging mockup for [BRAND NAME], showcasing a complete visual identity collection with a clean, modern, minimalist aesthetic. Arrange coordinated packaging, stationery, marketing materials, and promotional items around a central hero poster featuring the brand's campaign title and lifestyle imagery. Include product bags, boxes, takeaway cups, business cards, postcards, tags, stickers, menu cards, tickets, and branded inserts, all designed with a cohesive color palette of [PRIMARY COLOR], [SECONDARY COLOR], and [ACCENT COLOR]. Use elegant sans-serif typography, a simple geometric or line-art logo, subtle props like binder clips or paper clips, and balanced spacing for a curated editorial look. Capture the scene from a perfectly overhead perspective with soft natural lighting, realistic shadows, premium paper textures, and photorealistic detail suitable for a professional brand identity presentation.",
      "prompt_ko": "[브랜드명]을 위한 프리미엄 플랫레이 탑다운 브랜딩+패키징 목업 생성. 깔끔하고 모던·미니멀한 미학으로 완전한 비주얼 아이덴티티 컬렉션을 보여줌. 중앙의 히어로 포스터(캠페인 타이틀+라이프스타일 이미지) 주위로 패키징·문구류·마케팅 자료·판촉물을 정돈 배치. 제품백·박스·테이크아웃 컵·명함·엽서·태그·스티커·메뉴카드·티켓·브랜드 인서트 포함, 모두 [주색]·[보조색]·[강조색]의 일관된 팔레트로 디자인. 우아한 산세리프 타이포, 단순 기하/라인아트 로고, 바인더클립 같은 소품, 균형 잡힌 여백으로 큐레이티드 에디토리얼 룩. 완벽한 오버헤드 시점, 부드러운 자연광, 사실적 그림자, 프리미엄 종이 질감, 포토리얼 디테일로 프로페셔널 브랜드 아이덴티티 프레젠테이션용.",
      "ref_image": "https://pbs.twimg.com/media/HL8bX3QbYAAoyI4.jpg",
      "result": "results/lucia-1.png",
      "seed": 730217671
    },
    {
      "id": "derek-1",
      "source": "https://x.com/derek_wall90176/status/2071516180292976779",
      "author": "@derek_wall90176",
      "date": "2026-06-29",
      "lang": "zh",
      "target_model": "GPT-Image-2",
      "category": "타이포 포스터",
      "title": "대형 한자 + 물체 관통 포스터 (图文一体)",
      "prompt": "生成一张极具平面设计感的中文海报。\n画面中央使用超大字号的中文黑体字：\"【关键词】\"，文字占据主要视觉区域，笔画粗壮、清晰、准确，具有强烈的结构感。\n一个\"【物体】\"从文字的笔画缝隙之间自然穿过，形成明确的前后遮挡关系和空间穿插关系。\n背景使用\"【纯色背景】\"，整体加入半调颗粒质感、轻微印刷感和街头海报感。\n风格要求：强对比 / 纯色块 / 图文一体 / 中文排版准确 / 具有先锋杂志内页、展览海报和街头艺术海报的混合气质。\n不要做成普通插画海报，不要让文字只是装饰，不要把物体简单贴在文字前面，而是要让物体真正进入文字空间。\n核心结构 = 一个大字 + 一个物体 + 一个穿插关系 + 一个高对比背景 + 一种印刷质感。\n——————\n替换示例：\n关键词:坐｜物体:木椅｜背景:朱红色 / 关键词:飞｜物体:纸飞机｜背景:深蓝色 / 关键词:光｜物体:棱镜光束｜背景:黑色 / 关键词:书｜物体:翻开的书页｜背景:米白色 / 关键词:山｜物体:山峰轮廓｜背景:灰绿色",
      "prompt_ko": "강한 그래픽 디자인 감각의 중국어 포스터를 생성한다.\n화면 중앙에 초대형 중국어 고딕(흑체) 글자: \"【키워드】\" — 텍스트가 주요 시각 영역을 차지하고 획이 굵고 선명·정확하며 강한 구조감.\n하나의 \"【물체】\"가 글자 획 사이 틈으로 자연스럽게 관통하여 명확한 전후 가림·공간 교차 관계를 형성.\n배경은 \"【단색 배경】\", 전체에 하프톤 입자 질감·약한 인쇄감·스트리트 포스터 느낌 추가.\n스타일 요구: 강대비 / 단색 색면 / 이미지-텍스트 일체 / 정확한 중국어 타이포 / 아방가르드 잡지 내지·전시·스트리트 아트 포스터가 섞인 기질.\n일반 일러스트 포스터로 만들지 말 것, 텍스트를 장식으로만 쓰지 말 것, 물체를 글자 앞에 붙이지 말 것 — 물체가 진짜 글자 공간으로 들어가게 할 것.\n핵심 구조 = 큰 글자1 + 물체1 + 관통 관계1 + 고대비 배경1 + 인쇄 질감1.\n——————\n치환 예시:\n坐(앉다)｜나무의자｜주홍 / 飞(날다)｜종이비행기｜짙은파랑 / 光(빛)｜프리즘·광선｜검정 / 书(책)｜펼친 책장｜미백 / 山(산)｜산봉우리 실루엣｜회녹",
      "ref_image": "https://pbs.twimg.com/media/HL96mHJacAAIm1T.jpg",
      "result": "results/derek-1.png",
      "seed": 1206344900,
      "gen_prompt": "Bold graphic-design poster. A GIANT bold sans-serif ENGLISH word dominates the center (the word 'SIT'), with thick, clean, accurate strokes, strong structure, occupying the main visual area. An object (a wooden chair) passes naturally THROUGH the gaps between the letter strokes, creating clear front-back occlusion and spatial interpenetration — the object truly enters the letter space, not pasted in front of it. Solid pure vermilion-red background, halftone grain, slight print texture, street-poster feel. High contrast, solid color blocks, image-text integration; an avant-garde magazine-spread / exhibition / street-art poster mix. Core structure = one big ENGLISH word + one object + interpenetration + high-contrast background + print texture. All text in clean legible English only."
    },
    {
      "id": "promptlab-1",
      "source": "https://x.com/iamaiistudio/status/2071683274725028140",
      "author": "@iamaiistudio",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT Image 2",
      "category": "로고/배지",
      "title": "Y2K 하라주쿠 브랜드 배지 시스템",
      "prompt": "[BRAND NAME]\nYou are a senior vector designer specializing in Y2K Harajuku badge art. Your world: Tokyo bootleg culture, early 2000s Japanese brand remixes, retro-futuristic sticker aesthetics. Every output should look like a clean Illustrator vector file, flat and sticker-ready. The badge structure must be invented fresh for each brand, not templated.\nBRAND ANALYSIS — resolve all: (1) PRIMARY COLOR (brand main color softened into pastel Y2K); (2) ACCENT COLOR (secondary pushed to warm saturation); (3) DARK COLOR (deep palette for outlines/extrusions); (4) LETTER CONTENT (brand name in bold lowercase or iconic abbreviation); (5) KATAKANA (correct Japanese transliteration); (6) ORIGIN FLAG (country-of-origin flag as small flat element); (7) SHAPE LANGUAGE (iconic geometric forms from brand identity as orbital/background elements, never generic ovals); (8) CULTURAL SYMBOLS (1-2 small iconic objects rendered as tiny flat illustrations); (9) COMPOSITION LOGIC (layout invented specifically for this brand).\nCANVAS — 1:1 square. Flat off-white or warm light grey background. Completely empty, no texture, no gradient.\nBADGE STRUCTURE — central lettering element, surrounding brand-specific shapes with z-layer stacking, at least one element passing both behind and in front of the letters for depth, unified badge/patch silhouette. Shapes must feel inevitable to this brand.\nLETTERING — brand name in large bold lowercase, wide rounded display typeface. Flat PRIMARY COLOR fill. Thick DARK COLOR extrusion offset down-right 8-12% of letter height. Bold DARK COLOR outline. No gradients.\nY2K SIGNATURE ELEMENTS — speed lines/motion texture in ACCENT inside background shapes; sharp 4-point star accent in DARK near lettering; KATAKANA tucked into composition; ORIGIN FLAG small accurate flat element; brand cultural symbol as tiny flat illustration.\nTECH SPECS — flat vector only, zero gradients/effects/blur. Clean crisp edges. Max 4 colors: PRIMARY pastel, ACCENT warm saturated, DARK outline, off-white. Must feel like a collectible sticker or embroidered patch.",
      "prompt_ko": "[브랜드명]\n당신은 Y2K 하라주쿠 배지 아트 전문 시니어 벡터 디자이너. 세계관: 도쿄 부틀렉 문화, 2000년대 초 일본 브랜드 리믹스, 레트로-퓨처 스티커 미학. 모든 결과물은 깔끔한 일러스트레이터 벡터 파일처럼 플랫하고 스티커로 바로 쓸 수 있어야 함. 배지 구조는 브랜드마다 새로 발명(템플릿 금지).\n브랜드 분석 — 다음을 모두 결정: (1)주색=브랜드 메인색을 파스텔 Y2K로 부드럽게 (2)강조색=보조색을 따뜻한 채도로 (3)다크색=외곽선·돌출용 짙은 색 (4)글자내용=브랜드명 볼드 소문자/상징적 약어 (5)카타카나=정확한 일본어 음차 (6)원산지 국기=작은 플랫 요소 (7)셰이프 랭귀지=브랜드 아이덴티티의 상징적 기하 형태를 궤도·배경 요소로(일반 타원 금지) (8)문화 심볼=브랜드 세계의 작은 아이콘 1-2개를 작은 플랫 일러스트로 (9)구성 로직=이 브랜드 전용 레이아웃.\n캔버스 — 1:1 정사각. 플랫 오프화이트/따뜻한 라이트그레이 배경. 완전히 비움(텍스처·그라데이션 없음).\n배지 구조 — 중앙 레터링, 주위에 브랜드별 형태를 z-레이어 스택, 최소 하나는 글자 앞뒤를 모두 통과해 깊이감, 통일된 배지/패치 실루엣.\n레터링 — 브랜드명 큰 볼드 소문자, 넓은 둥근 디스플레이 서체. 주색 플랫 채움. 글자 높이 8-12% 우하향 다크색 돌출. 볼드 다크 외곽선. 그라데이션 없음.\nY2K 시그니처 — 배경 형태 안에 강조색 스피드라인/모션 텍스처; 레터링 근처 다크색 날카로운 4각별; 카타카나 자연스럽게 삽입; 원산지 국기 작은 플랫 요소; 브랜드 문화 심볼 작은 플랫 일러스트.\n테크 스펙 — 플랫 벡터만, 그라데이션·이펙트·블러 제로. 깔끔한 엣지. 최대 4색: 파스텔 주색·따뜻한 강조색·다크 외곽·오프화이트. 수집용 스티커/자수 패치 느낌.",
      "ref_image": "https://pbs.twimg.com/media/HMAYhWtbUAAhQLy.jpg",
      "result": "results/promptlab-1.png",
      "seed": 848735499
    },
    {
      "id": "naik-1",
      "source": "https://x.com/naiknelofar788/status/2071610668521034222",
      "author": "@Naiknelofar788",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT image 2",
      "category": "스타일 변환",
      "title": "사진→흑백 치비 두들 변환",
      "prompt": "Convert the uploaded photo into a cute black-and-white hand-drawn doodle illustration in the exact style of a minimalist marker sketch. Preserve the original composition, pose, camera angle, facial expressions, clothing, and positioning of all subjects. Transform the people into adorable chibi/cartoon characters with simplified features, large expressive eyes, rounded faces, and clean outlines.",
      "prompt_ko": "업로드한 사진을 미니멀 마커 스케치 스타일의 귀여운 흑백 손그림 두들 일러스트로 변환. 원본의 구도·포즈·카메라 앵글·표정·의상·모든 인물 배치를 보존. 인물을 단순화된 이목구비, 크고 표현력 있는 눈, 둥근 얼굴, 깔끔한 외곽선의 사랑스러운 치비/만화 캐릭터로 변환.\n※ i2i 변환 프롬프트(원본 사진 필요) — Krea2 t2i는 두들 치비 스타일 인물 생성만.",
      "ref_image": "https://pbs.twimg.com/media/HL_W6wYboAA-FH0.jpg",
      "result": "results/naik-1.png",
      "seed": 2048042913
    },
    {
      "id": "aziz-1",
      "source": "https://x.com/aziz4ai/status/2071674030998933562",
      "author": "@aziz4ai",
      "date": "2026-06-30",
      "lang": "en",
      "target_model": "GPT Image 2",
      "category": "제품 광고",
      "title": "제품 분해(exploded-view) 광고 포스터",
      "prompt": "Create a premium advertising poster for [BRAND] featuring [PRODUCT].\nBuild the poster as a cinematic exploded-view composition where the product appears suspended in space, separated into its essential layers, materials, ingredients, components, textures, or sensory elements.\nThe goal is not technical instruction. The goal is visual storytelling.\nEvery floating layer should reveal something meaningful about the product:\n- tech products reveal precision, lenses, chips, screens, light, signals, glass, metal, and intelligence\n- food products reveal flavor, texture, ingredients, crumbs, cream, steam, sauce, crunch, or freshness\n- beverage products reveal liquid energy, bubbles, ice, fruit, condensation, motion, and refreshment\n- fashion products reveal fabric, stitching, sole structure, leather, mesh, motion, identity, and lifestyle\n- beauty products reveal scent, botanicals, liquid, glass, skin glow, mist, ritual, and refinement\n- luxury products reveal craft, heritage, materials, polish, shadows, and timeless design\nKeep the product accurate, recognizable, sharp, and visually dominant.\nArrange the exploded elements with premium art direction, cinematic lighting, clean depth, polished reflections, strong negative space, dramatic shadows, and a clear visual hierarchy.\nThe image should feel like a world-class campaign poster: iconic, expensive, scroll-stopping, and specifically designed for this exact brand and product.\nDo not use miniature people, tiny worlds, product monuments, or city-scale scenes.\nAdd tasteful poster typography inspired by the brand's visual language, with a short 3-word slogan.\nAvoid copying any existing campaign. Create a fresh original visual system.\nAspect ratio: [RATIO]",
      "prompt_ko": "[브랜드]의 [제품]을 위한 프리미엄 광고 포스터 생성.\n제품이 공간에 떠 있고 핵심 레이어·소재·성분·부품·질감·감각 요소로 분해된 시네마틱 익스플로디드뷰(분해도) 구성으로 빌드.\n목표는 기술 설명이 아니라 비주얼 스토리텔링.\n떠 있는 각 레이어가 제품의 의미를 드러냄:\n- 테크=정밀·렌즈·칩·스크린·빛·신호·유리·메탈·지능\n- 식품=풍미·질감·재료·부스러기·크림·증기·소스·바삭함·신선함\n- 음료=액체 에너지·기포·얼음·과일·물방울·움직임·청량함\n- 패션=원단·스티칭·밑창 구조·가죽·메시·움직임·정체성·라이프스타일\n- 뷰티=향·식물·액체·유리·피부 광채·미스트·리추얼·정제미\n- 럭셔리=장인정신·헤리티지·소재·광택·그림자·타임리스 디자인\n제품은 정확·인식가능·선명·시각적으로 지배적으로 유지.\n분해 요소를 프리미엄 아트디렉션·시네마틱 조명·깔끔한 깊이감·광택 반사·강한 여백·드라마틱 그림자·명확한 시각 위계로 배치.\n세계적 캠페인 포스터처럼 상징적·고급·시선 사로잡는 느낌, 이 브랜드·제품 전용 설계.\n미니어처 인물·작은 세계·제품 기념비·도시 규모 장면 금지.\n브랜드 비주얼 언어에서 영감받은 세련된 포스터 타이포 + 짧은 3단어 슬로건.\n기존 캠페인 베끼지 말고 새 오리지널 비주얼 시스템. 종횡비: [비율]",
      "ref_image": null,
      "result": "results/aziz-1.png",
      "seed": 1615646144
    },
    {
      "id": "zephyra-1",
      "source": "https://x.com/zephyraleigh/status/2071554035312939305",
      "author": "@ZephyraLeigh",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "범용",
      "category": "캐리커처",
      "title": "빅헤드 캐리커처 (큰 머리·작은 몸)",
      "prompt": "Hilarious stylized digital caricature of [SUBJECT], featuring an oversized head, tiny elegant body, exaggerated smile, oversized expressive eyes, cartoonishly playful proportions, vibrant painterly illustration, dramatic studio lighting, 8K.",
      "prompt_ko": "[대상]의 유쾌한 스타일라이즈드 디지털 캐리커처. 큰 머리, 작고 우아한 몸, 과장된 미소, 크고 표현력 있는 눈, 만화처럼 장난스러운 비율, 생기 있는 페인터리 일러스트, 드라마틱 스튜디오 조명, 8K.",
      "ref_image": "https://pbs.twimg.com/media/HL8iG57b0AAyQTU.jpg",
      "result": "results/zephyra-1.png",
      "seed": 1230507835
    },
    {
      "id": "meng-1",
      "source": "https://x.com/meng_dagg695/status/2071457338998067385",
      "author": "@meng_dagg695",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT image 2 (ImagineArt)",
      "category": "초현실 콜라주",
      "title": "해바라기 자전거 바퀴 — 흑백+선택적 옐로우 콜라주",
      "prompt": "Surreal mixed-media collage artwork, black and white photograph of young woman with sleek dark bob haircut riding a bicycle in side profile, head tilted upward joyfully, wearing selectively colored bright yellow polka-dot dress coat, yellow cat-eye sunglasses, yellow knee socks, entire scene rendered in grayscale except for vivid yellow elements (her outfit and the bicycle frame), bicycle wheels illustrated as large detailed yellow sunflowers with dark centers replacing the spokes, subtle motion blur on the sunflower petals suggesting movement, surreal clouds made of collaged vintage newspaper texture and ink illustration, grainy textured finish on the yellow elements, small illustrated birds among the clouds, grassy ground in fine ink linework, vertical 4:5 composition, artistic conceptual collage photography.",
      "prompt_ko": "초현실 믹스드미디어 콜라주. 매끈한 다크 보브컷 젊은 여성이 자전거를 측면으로 타며 고개를 즐겁게 위로 든 흑백 사진. 선택적으로 채색된 밝은 노랑 폴카도트 드레스코트·노랑 캣아이 선글라스·노랑 무릎양말. 전체는 그레이스케일이되 의상과 자전거 프레임 등 노랑 요소만 선명. 자전거 바퀴는 스포크 대신 어두운 중심의 크고 디테일한 노랑 해바라기, 꽃잎에 미세 모션블러로 움직임 암시. 하늘 구름은 빈티지 신문 텍스처+잉크 일러스트 콜라주, 노랑 요소엔 거친 질감, 구름 사이 작은 새, 잉크 라인워크 잔디 바닥. 세로 4:5 컨셉추얼 콜라주 사진.",
      "ref_image": null,
      "result": "results/meng-1.png",
      "seed": 759817794
    },
    {
      "id": "anisha-1",
      "source": "https://x.com/Anishaa_writes/status/2071511491937718653",
      "author": "@Anishaa_writes",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "범용",
      "category": "미니멀 포스터",
      "title": "미니멀 두들 라인아트 포스터 (CREATE EVERY DAY)",
      "prompt": "Minimal editorial wall poster celebrating creativity with elegant black line illustrations of a pencil, paintbrush, notebook, camera, keyboard, scissors, color palette, ruler, paper clips, sticky notes, light bulb, and subtle abstract accents. Airy asymmetrical layout with generous negative space on a soft ivory textured background. Centered title \"CREATE EVERY DAY\" in refined modern typography. Clean monochrome vector line art, contemporary studio aesthetic, handcrafted minimalism, premium gallery-style poster.",
      "prompt_ko": "창의성을 기리는 미니멀 에디토리얼 월 포스터. 연필·붓·노트·카메라·키보드·가위·색팔레트·자·클립·포스트잇·전구 등을 우아한 검정 라인 일러스트로. 부드러운 아이보리 텍스처 배경에 여백 넉넉한 비대칭 레이아웃. 중앙 타이틀 \"CREATE EVERY DAY\" 세련된 모던 타이포. 깔끔한 모노크롬 벡터 라인아트, 컨템포러리 스튜디오 미학, 핸드크래프트 미니멀리즘, 프리미엄 갤러리 포스터.",
      "ref_image": null,
      "result": "results/anisha-1.png",
      "seed": 100113395
    },
    {
      "id": "gdgtify-1",
      "source": "https://x.com/Gdgtify/status/2071492111296258326",
      "author": "@Gdgtify",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "범용",
      "category": "팝업북/디오라마",
      "title": "페이퍼크래프트 팝업북 광고 디오라마",
      "prompt": "This papercraft pop-up book prompt works for any product. <instruction> 1. Brand Deconstruction: Input a famous consumer brand/product/mascot. Deconstruct into 4 assets — The Mascot/Hero (iconic character or product shape), The Environment (idealized origin setting), The Typography (catchphrase + logo), The Consumer (target audience as secondary characters). 2. Container (Pop-Up Box): goal = 'Interactive Packaging' diorama photography. The base is the actual cardboard packaging box, lying flat, opened like a book; original branding/logos/info visible on the front edge. Setting: warm sunlit wooden kitchen/dining table. 3. Diorama (Paper Engineering): complex pop-up book art; everything erupting from the open box built from layered printed folded cardstock; visible tabs, creases, 'Pull' arrow mechanisms required. Background = layered paper landscape from the Environment (e.g. rising paper sun + cornfields). Foreground = the Mascot bursts forward as a large multi-layered paper cutout. Center = a giant stylized paper representation of the product. 4. Narrative Scale: smaller paper cutouts of Consumers interacting with the giant product; large curved paper banners across the top with the Slogan; small wooden-style paper signs with extra brand messaging. 5. Lighting & Atmosphere: sunny morning light, warm golden directional from top-left window, sharp distinct shadows behind paper layers emphasizing 3D pop-up depth; high fidelity cardboard thickness, matte printed ink, scissor-cut edges. Output: ONE image, 16:9, 3D render/macro photography, 'Nostalgic Papercraft' aesthetic, vibrant commercial colors. </instruction>",
      "prompt_ko": "어떤 제품이든 페이퍼크래프트 팝업북으로. [지시] 1.브랜드 해체: 유명 브랜드/제품/마스코트 입력→마스코트(히어로)·환경(기원)·타이포(슬로건)·소비자 4요소 추출. 2.컨테이너(팝업박스): '인터랙티브 패키징' 디오라마 사진. 실제 제품 패키지 박스가 책처럼 펼쳐져 평평히 누움, 로고·정보는 박스 앞면 가장자리에 보임. 따뜻한 햇살 나무 식탁. 3.디오라마(페이퍼 엔지니어링): 복잡한 팝업북 아트, 박스에서 솟는 모든 게 인쇄·접힌 카드스톡, 탭·접힘선·'당김' 화살표 필수. 배경=환경 기반 종이 풍경(떠오르는 종이 해+옥수수밭). 전경=마스코트가 큰 다층 종이 컷아웃으로 돌출. 중앙=거대 스타일화 종이 제품. 4.내러티브 스케일: 소비자 종이 컷아웃이 거대 제품과 상호작용, 상단 곡선 종이 배너에 슬로건, 작은 나무풍 종이 표지판. 5.조명: 맑은 아침 햇살(좌상단 창), 종이층 뒤 선명한 그림자로 3D 깊이, 골판지 두께·매트 잉크·가위 자른 엣지. 출력: 1장, 16:9, 3D렌더/매크로, 노스탤직 페이퍼크래프트, 비비드 커머셜 컬러.",
      "ref_image": null,
      "result": "results/gdgtify-1.png",
      "seed": 702539797
    },
    {
      "id": "lucia2-1",
      "source": "https://x.com/luciaverseai/status/2071272641512743202",
      "author": "@luciaverseai",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "범용",
      "category": "3D 캐릭터 액션",
      "title": "캐릭터 타이포 돌파(punch-through-text) 3D 액션",
      "prompt": "A high-energy 3D digital artwork of a [CHARACTER NAME] from [FRANCHISE/SHOW] bursting forward in an aggressive mid-air action pose, with a fierce expression and dynamic foreshortened perspective. The character is centered and rendered in a glossy, highly detailed stylized 3D look, matching their signature outfit, colors, and iconic features. They are breaking through a massive cracked 3D stone typography of their name, which explodes into flying debris against a dark background. Powerful energy effects (lightning, aura, or glow) in [PRIMARY COLOR] radiate through the shattered letters, casting dramatic highlights and enhancing motion. Bold complementary color palette, cinematic lighting, high contrast, and extreme depth create a dramatic punch-through-text impact composition.",
      "prompt_ko": "[캐릭터]([프랜차이즈/쇼])가 공격적 공중 액션 포즈로 돌진하는 고에너지 3D 디지털 아트워크. 사나운 표정, 역동적 단축 원근. 캐릭터는 중앙, 광택 있고 디테일한 스타일라이즈드 3D, 시그니처 의상·색·특징 유지. 자기 이름의 거대한 균열 3D 돌 타이포를 뚫고 나오며 파편이 어두운 배경으로 폭발. [주색]의 강력한 에너지 이펙트(번개·오라·글로우)가 부서진 글자 사이로 방사, 드라마틱 하이라이트+모션. 대담한 보색 팔레트, 시네마틱 조명, 고대비, 극단적 깊이로 '텍스트 돌파' 임팩트 구성.",
      "ref_image": null,
      "result": "results/lucia2-1.png",
      "seed": 381996493
    },
    {
      "id": "yang-1",
      "source": "https://x.com/YangOnchain/status/2071603453839958510",
      "author": "@YangOnchain",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "범용",
      "category": "드림코어 포스터",
      "title": "드림코어 어류 떼 감성 포스터 (안개·여백·그레인)",
      "prompt": "General Prompt: Generate a vertical 3:4 art poster, a fully completed and laid-out finished poster.\nThe theme is [Theme] — not ordinary ocean photography nor ordinary fish illustration, but a conceptual poster with strong emotional temperament, dreamlike feel, atmospheric vibe, design sensibility.\n[Core Visual] Center on [school of fish / jellyfish / tropical fish / glowing fish / translucent marine creatures / floating objects / sea-surface light] as the main subject, but heavily surreal — do not replicate realistically; transform into a striking artistic image. Incorporate: hazy mist, gradient seawater, floating particles, soft focus, light halos, subtle grain, blurred edges, dreamcore atmosphere, low-contrast background, ethereal negative space, floating composition.\n[Composition] Clear focal point; large negative space, off-center, floating layout, poster-style cropping, upper/lower layering, rhythmic density, depth contrast, single-side title, corner info. Like a genuine design poster, not a wallpaper.\n[Color & Atmosphere] Palette around [primary color: coral orange / misty pink / sea-salt blue / deep-sea black / neon purple / gray-green / amber gold]. Unified, soft, airy; subtle film grain, matte, slight print effect. Keywords: serene, ethereal, melancholic, healing, hazy, dreamy, surreal, poetic.\n[Text Layout] Complete typesetting in the image — Main title: [Main Title] / Subtitle: [short copy] / fine print [1/2/3]. Restrained sophisticated, no advertising vibe, no clutter. No real brand names, watermarks, garbled text, or dates.\n[Texture] High-end art-poster texture, soft-focus photo feel, dreamy ocean atmosphere, printed grain, modern design. Output: complete finished poster.",
      "gen_prompt": "General Prompt: Generate a vertical 3:4 art poster, a fully completed and laid-out finished poster.\nThe theme is [Theme] — not ordinary ocean photography nor ordinary fish illustration, but a conceptual poster with strong emotional temperament, dreamlike feel, atmospheric vibe, design sensibility.\n[Core Visual] Center on [school of fish / jellyfish / tropical fish / glowing fish / translucent marine creatures / floating objects / sea-surface light] as the main subject, but heavily surreal — do not replicate realistically; transform into a striking artistic image. Incorporate: hazy mist, gradient seawater, floating particles, soft focus, light halos, subtle grain, blurred edges, dreamcore atmosphere, low-contrast background, ethereal negative space, floating composition.\n[Composition] Clear focal point; large negative space, off-center, floating layout, poster-style cropping, upper/lower layering, rhythmic density, depth contrast, single-side title, corner info. Like a genuine design poster, not a wallpaper.\n[Color & Atmosphere] Palette around [primary color: coral orange / misty pink / sea-salt blue / deep-sea black / neon purple / gray-green / amber gold]. Unified, soft, airy; subtle film grain, matte, slight print effect. Keywords: serene, ethereal, melancholic, healing, hazy, dreamy, surreal, poetic.\n[Text Layout] Complete ENGLISH typesetting in the image — Main title: [English main title] / Subtitle: [short copy] / fine print [1/2/3]. Restrained sophisticated, no advertising vibe, no clutter. No real brand names, watermarks, garbled text, or dates.\n[Texture] High-end art-poster texture, soft-focus photo feel, dreamy ocean atmosphere, printed grain, modern design. Output: complete finished poster. | All visible text/typography in ENGLISH only.",
      "prompt_ko": "세로 3:4 아트 포스터(완전히 완성·레이아웃). 테마 [테마] — 평범한 바다 사진·물고기 일러스트가 아니라 강한 감성·몽환·분위기의 컨셉추얼 포스터. [핵심] 어류 떼/해파리/열대어/발광어/반투명 해양생물/수면 빛을 주제로 하되 사실 복제 금지, 초현실 변형. 안개·그라데이션 바닷물·부유 입자·소프트포커스·광륜·미세 그레인·흐린 엣지·드림코어·저대비·이서리얼 여백·부유 구성. [구성] 명확한 초점, 넓은 여백·오프센터·포스터 크롭·상하 레이어링·깊이 대비. [색·분위기] [주색](코랄오렌지/미스티핑크/씨솔트블루/딥씨블랙/네온퍼플/그레이그린/앰버골드) 중심, 통일·부드러움·에어리, 필름그레인·매트. 키워드: 고요·이서리얼·멜랑콜릭·힐링·헤이지·드리미·초현실·시적. [텍스트] 완전한 타이포(메인타이틀/부제/카피/파인프린트), 절제·세련, 광고티·잡동사니 금지, 실제 브랜드명·워터마크·오타·날짜 금지. [질감] 하이엔드 아트포스터·소프트포커스·몽환 바다·인쇄 그레인. 출력: 완성 포스터. (원문은 중국어 타이포 명시 → 영어 텍스트로 생성)",
      "ref_image": null,
      "result": "results/yang-1.png",
      "seed": 1278335829
    },
    {
      "id": "yang-2",
      "source": "https://x.com/YangOnchain/status/2071531426135355503",
      "author": "@YangOnchain",
      "date": "2026-06-29",
      "lang": "zh",
      "target_model": "GPT image 2",
      "category": "동양 건축 포스터",
      "title": "동양 건축 공간 장권 포스터 (가로 16:9 스크롤)",
      "prompt": "生成一张横版 16:9 的东方建筑场景海报，必须是一张已经完成中文排版的成品海报。\n整体风格为：东方空间长卷、中式建筑概念设计、建筑模型感、山水意境、现代建筑剖面、场景叙事海报、高级留白、中文竖排排版、博物馆展板质感。\n画面主体是一座以【主题方向】为核心的中式建筑空间。建筑不是普通房子，而是一条横向展开的空间长卷，拥有连续起伏的曲线屋顶，屋顶像山脊、琴弦、纸卷、药草坡、书页、月牙、船篷或织机曲线一样延展。建筑下方或内部采用玻璃剖面结构，可以看到不同房间、人物活动、家具陈设与空间功能。\n画面采用横向构图，大面积留白，背景为米白、宣纸色、淡墨灰、雾白或夜色深黑。远处可以有淡淡山影、云雾、水面、庭院、坡地、树木、台阶、池塘或荒漠，但整体必须克制，不要拥挤。\n建筑内部需要有微型人物活动，人物穿着古代或新中式服饰，正在进行与主题相关的行为，例如：问诊、煎药、按摩、抚琴、品茶、读书、抄经、制香、染布、织造、泡汤、观月、修复壁画、做实验、整理器物。人物要小而精致，像建筑模型中的生活场景，不要抢主体。\n海报必须包含中文竖排标题：「【主标题】」。可加入一到两组竖排副文案：「【副标题】」「【短句】」。中文排版要像东方展览海报、古籍题签、建筑展板或文人画题跋。文字要克制，放在画面左侧或右侧留白处，不能压乱建筑主体。可以加入小印章、小号题注、细线、馆藏式标识，但不要真实品牌 Logo。\n画面质感：纸张纹理、轻微颗粒、柔和雾气、低饱和色彩、建筑模型级细节、电影感光影、克制高级、安静叙事。\n构图要求：建筑横向展开，占画面下半部分或中下部；上半部分保留大量空气感留白；水面、台地或坡地作为前景；远山或雾气作为背景；中文竖排文字与建筑形成平衡。\n不要：不要普通房地产效果图，不要现代商业售楼处，不要杂乱国潮，不要大红大金，不要电商海报，不要水印，不要真实 Logo，不要把人画得太大，不要复杂拥挤背景。",
      "gen_prompt": "Create a horizontal 16:9 Oriental architecture scene poster, a fully finished poster with completed typography. Style: Oriental spatial handscroll, Chinese architectural concept design, architectural-model feel, shanshui landscape mood, modern architectural section, narrative scene poster, refined negative space, elegant vertical typography, museum exhibition-board texture.\nMain subject: a Chinese architectural space themed around [THEME]. Not an ordinary house but a horizontally unfolding spatial scroll with continuous undulating curved roofs extending like mountain ridges, zither strings, paper scrolls, herb slopes, book pages, crescent moons, boat canopies or loom curves. A glass sectional structure below/inside reveals different rooms, human activities, furniture and functions.\nHorizontal composition, large negative space, background in off-white / rice-paper / light ink-grey / misty white / deep night-black. Faint distant mountains, mist, water, courtyards, slopes, trees, steps, ponds — restrained, never crowded.\nInside, miniature human figures in ancient or neo-Chinese attire perform theme-related actions (consulting, brewing herbs, massage, zither, tea, reading, copying scripture, making incense, dyeing, weaving, hot-spring, moon-watching, restoring murals, experiments, arranging objects), small and exquisite like a life scene in an architectural model, not stealing the subject.\nThe poster must include an elegant title and typography — ALL TEXT IN ENGLISH: main title [MAIN TITLE], optional subtitle [SUBTITLE] / [short phrase], placed in the left or right negative space without cluttering the architecture. Small seals, captions, fine lines and archival marks allowed, but no real brand logos.\nTexture: paper grain, slight grain, soft mist, low saturation, model-level detail, cinematic light, restrained refined quiet narrative. Composition: architecture spans horizontally in the lower/center-lower; upper half keeps airy negative space; water/terrace as foreground; distant mountains/mist as background. Avoid: real-estate renders, sales-office look, messy guochao, big red-and-gold, e-commerce posters, watermarks, real logos, oversized people, crowded backgrounds. | All visible text/typography in ENGLISH only.",
      "prompt_ko": "가로 16:9 동양 건축 장면 포스터(타이포 완성품). 스타일: 동양 공간 장권·중식 건축 컨셉·건축모형감·산수 의경·현대 건축 단면·서사 포스터·고급 여백·(세로) 타이포·박물관 전시판 질감.\n주체: [테마] 중심의 중식 건축 공간. 평범한 집이 아니라 가로로 펼쳐지는 공간 장권, 연속 기복하는 곡선 지붕(산등성이·거문고줄·종이두루마리·약초비탈·책장·초승달·뱃지붕·베틀 곡선처럼). 하부/내부 유리 단면으로 방·인물활동·가구·기능이 보임.\n가로 구성, 넓은 여백, 배경은 미백·선지색·담묵회·안개백·심야흑. 먼 산그림자·운무·수면·정원·비탈·나무·계단·연못, 단 절제(빽빽 금지).\n내부 미니어처 인물(고대/신중식 의상)이 테마 행위: 진찰·약달이기·안마·거문고·차·독서·사경·향만들기·염색·직조·온천·달구경·벽화복원·실험·기물정리. 작고 정교하게, 주체 안 뺏게.\n세로 타이틀 + 부제/짧은 문구(좌우 여백, 건축 안 가리게), 작은 인장·제주·세선·소장표식 OK, 실제 로고 금지.\n질감: 종이결·미세 그레인·부드러운 안개·저채도·모형급 디테일·시네마틱 광영·절제 고급·고요 서사. 구성: 건축 가로전개(하단/중하), 상단 여백, 수면/대지 전경, 원산/안개 배경. 금지: 부동산효과도·분양사무소·잡다 국조·대홍대금·이커머스 포스터·워터마크·실제로고·과대인물·복잡배경.\n※ 원문은 중국어 세로 타이포 명시 → 제이크 정책에 따라 영어 텍스트로 생성.",
      "ref_image": null,
      "result": "results/yang-2.png",
      "seed": 379907236
    },
    {
      "id": "larus-1",
      "source": "https://x.com/MrLarus/status/2071534054520799279",
      "author": "@MrLarus",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT-Image2",
      "category": "로고",
      "title": "흑백 브랜드 로고 프레젠테이션 (아이콘+워드마크)",
      "prompt": "Create one original black-and-white brand logo presentation.\nBrand name: [BRAND NAME] / Subtitle: [SHORT SUBTITLE] / Category: [BRAND CATEGORY] / Mood: [MINIMAL / PREMIUM / FUTURISTIC / ELEGANT / ARCHITECTURAL]\nDesign a clean white logo on a pure black background. Include a custom icon + wordmark system. The logo should feel like a professional designer portfolio piece: minimal, sharp, readable, high-contrast, brand-ready.\nUse subtle gray portfolio details if needed, such as thin divider lines, \"BRAND LOGO — 2026\", a small registration mark, or a tiny corner signature.\nAvoid colorful elements, poster style, 3D, mockups, complex illustration, mascot, messy layout, generic fonts, and multiple logos in one image.",
      "prompt_ko": "오리지널 흑백 브랜드 로고 프레젠테이션 1개. 브랜드명 [BRAND NAME] / 부제 [SHORT SUBTITLE] / 카테고리 [BRAND CATEGORY] / 무드 [미니멀·프리미엄·퓨처리스틱·엘레강트·건축적]. 순수 검정 배경에 깔끔한 흰 로고. 커스텀 아이콘+워드마크 시스템. 프로 디자이너 포트폴리오 작품처럼 미니멀·샤프·가독·고대비·브랜드 레디. 필요시 옅은 회색 포트폴리오 디테일(가는 구분선, \"BRAND LOGO — 2026\", 작은 등록마크, 모서리 서명). 금지: 컬러풀 요소·포스터풍·3D·목업·복잡 일러스트·마스코트·지저분한 레이아웃·제네릭 폰트·한 이미지에 여러 로고.",
      "ref_image": null,
      "result": "results/larus-1.png",
      "seed": 2130433989
    },
    {
      "id": "delulu-1",
      "source": "https://x.com/MissDelulu9/status/2071799872328454301",
      "author": "@MissDelulu9",
      "date": "2026-06-30",
      "lang": "en",
      "target_model": "GPT image 2",
      "category": "스타일 변환",
      "title": "사진→파스텔 페이퍼컷 동화 일러스트 변환",
      "prompt": "Transform the attached photo into a cute pastel paper-cut illustration while preserving the exact faces, hairstyles, expressions, pose, clothing, and composition. Place a small copy of the original photo in the top-left corner with a clean white border, and recreate the rest as a soft layered paper-cut artwork. Rounded characters, pastel colors, paper texture, soft shadows, dreamy sky, lush greenery, cozy storybook aesthetic, high-quality illustration. Vertical 9:16.",
      "prompt_ko": "첨부 사진을 정확한 얼굴·헤어·표정·포즈·의상·구도를 보존하며 귀여운 파스텔 페이퍼컷 일러스트로 변환. 좌상단에 원본 사진 작은 사본을 깔끔한 흰 테두리로 배치, 나머지는 부드러운 레이어드 페이퍼컷 아트워크로 재구성. 둥근 캐릭터, 파스텔 색, 종이 질감, 부드러운 그림자, 몽환 하늘, 무성한 녹음, 아늑한 동화책 미학, 고품질 일러스트. 세로 9:16. ※i2i 변환 프롬프트(원본 사진 필요).",
      "ref_image": null,
      "result": "results/delulu-1.png",
      "seed": 1842169810
    },
    {
      "id": "gdgtify-2",
      "source": "https://x.com/Gdgtify/status/2071552257301102793",
      "author": "@Gdgtify",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "Midjourney/범용",
      "category": "스케일 인포그래픽",
      "title": "마이크로→코스믹 스케일 사다리 (10× 줌, powers of ten)",
      "prompt": "A top-down scale ladder where the single theme of [THEME] is shown at [N] escalating orders of magnitude, microscopic on the left to vast/cosmic on the right, each step a 10x zoom out, the full ladder forming the silhouette of [SHAPE] ::5\nScale Logic: AI_INFER the correct subject of [THEME] at each magnitude — molecular, cellular, object, human, architectural, geographic, planetary, cosmic as applicable — each step scientifically plausible and visibly larger in implied scale ::5\nComposition: Strict left-to-right magnitude grid, even logarithmic spacing, clean silhouette edge, generous margin ::3\nMaterial Physics: Real accurate appearance at each scale, consistent matte finish, soft shadows ::2\nIllumination: Flat overhead softbox, no glare ::2\nTypography: Tiny scale-bar labels (nm, mm, m, km...) along the lower edge ::2\nRender Stack: Powers-of-ten ladder, magnitude flat-lay, scale-zoom collection, 8k ::1\nNegative: [inconsistent scale, repeated magnitude, broken silhouette, overlap, tilt, 3d perspective, hands] ::-1",
      "gen_prompt": "A top-down scale ladder where the single theme of [THEME] is shown at [N] escalating orders of magnitude, microscopic on the left to vast/cosmic on the right, each step a 10x zoom out, the full ladder forming the silhouette of [SHAPE]\nScale Logic: AI_INFER the correct subject of [THEME] at each magnitude — molecular, cellular, object, human, architectural, geographic, planetary, cosmic as applicable — each step scientifically plausible and visibly larger in implied scale\nComposition: Strict left-to-right magnitude grid, even logarithmic spacing, clean silhouette edge, generous margin\nMaterial Physics: Real accurate appearance at each scale, consistent matte finish, soft shadows\nIllumination: Flat overhead softbox, no glare\nTypography: Tiny scale-bar labels (nm, mm, m, km...) along the lower edge\nRender Stack: Powers-of-ten ladder, magnitude flat-lay, scale-zoom collection, 8k\nNegative: [inconsistent scale, repeated magnitude, broken silhouette, overlap, tilt, 3d perspective, hands]",
      "prompt_ko": "탑다운 스케일 사다리 — 단일 테마 [테마]를 [N]단계 자릿수로(왼쪽 미시→오른쪽 광대/우주), 각 단계 10× 줌아웃, 전체 사다리가 [형태] 실루엣을 이룸. 스케일 로직: 각 배율에서 [테마]의 올바른 대상을 AI 추론(분자·세포·물체·인간·건축·지리·행성·우주), 과학적으로 그럴듯하게·점점 크게. 구성: 엄격한 좌→우 배율 그리드, 균등 로그 간격, 깔끔한 실루엣 엣지, 넉넉한 여백. 재질: 각 스케일 실제 외관, 일관 매트, 부드러운 그림자. 조명: 평평한 오버헤드 소프트박스, 글레어 없음. 타이포: 하단에 작은 스케일바 라벨(nm·mm·m·km). 렌더: powers-of-ten 사다리, 8k. 네거티브: 일관성없는 스케일·반복·깨진 실루엣·겹침·기울기·3D원근·손. ※원문의 ::N은 Midjourney 가중치 → 생성 시 제거함.",
      "ref_image": null,
      "result": "results/gdgtify-2.png",
      "seed": 1939712168
    },
    {
      "id": "dairy-1",
      "source": "https://x.com/kingofdairyque/status/2071583536549622035",
      "author": "@kingofdairyque",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT image 2 (TopviewAI)",
      "category": "자동차/제품 포스터",
      "title": "미니멀 자동차 에디토리얼 포스터 (스펙 블록)",
      "prompt": "Minimalist automotive editorial poster for [CAR], 4:5. Show the car in [COLOR], front three-quarter view on the lower right, parked in [SCENE]. Use a clean split-layout design with a distinct graphic color palette, realistic commercial photography, crisp reflections, clean shadows, and premium magazine styling. Add the matching manufacturer wordmark at the top left, a small matching logo at the top right, and a huge translucent model text reading \"[MODEL]\" behind the composition. Include one short editorial sentence reading \"[LINE]\". Add one tiny side-profile car thumbnail, three compact info labels, and three bottom spec blocks: ENGINE, POWER, TORQUE. Modern sparse typography, lots of negative space, clean automotive brochure aesthetic.",
      "prompt_ko": "[자동차]를 위한 미니멀 자동차 에디토리얼 포스터, 4:5. [색상] 차를 우하단에 전면 3/4 뷰로 [장면]에 주차. 깔끔한 분할 레이아웃+뚜렷한 그래픽 색팔레트, 사실적 상업 사진, 선명한 반사·깔끔한 그림자, 프리미엄 매거진 스타일. 좌상단 제조사 워드마크, 우상단 작은 로고, 구성 뒤에 거대한 반투명 모델 텍스트 \"[모델]\". 짧은 에디토리얼 문장 \"[문구]\" 1개. 작은 측면 차 썸네일 1개, 컴팩트 정보 라벨 3개, 하단 스펙 블록 3개: ENGINE·POWER·TORQUE. 모던 희소 타이포, 넉넉한 여백, 깔끔한 자동차 브로셔 미학.",
      "ref_image": null,
      "result": "results/dairy-1.png",
      "seed": 796777287
    },
    {
      "id": "xxd-daily-1",
      "source": "https://x.com/xiaoxiaodong01/status/2071566349583687887",
      "author": "@xiaoxiaodong01",
      "date": "2026-06-30",
      "lang": "zh",
      "target_model": "GPT-image2",
      "category": "데일리 사인",
      "title": "확산 광감 데일리 사인 (분산 색안개 + 정보 여백)",
      "prompt": "围绕任意主题对象生成一张以扩散光感和信息留白为核心的视觉设计：让主题首先被转译成两到三团大尺度、边缘柔化的半透明色雾，彼此在画面中段交叠、穿插和轻微错位，形成像光晕渗开一样的主视觉，而不是清晰描边的实体插画；其中一团承载主题最强的情绪能量，面积最大、色彩最饱满，另一团作为辅助流动方向，第三层只作为淡淡的空气底色，使视觉从大片空白中慢慢显形。背景保持高明度、清透、干净，有通风感和柔和纸面颗粒，纹理像细密印刷噪点覆盖全画面，但不制造脏污、旧化或灰黄感。色彩从主题自身的材质、季节、品牌或情绪中提取，映射为明亮底色、情绪主色、辅助暖冷色、少量清晰强调色和深色信息文字；保留大面积轻亮底、少量高饱和发光色、柔和过渡和干净色阶的关系，让整体呈现明亮轻快、梦感但有秩序的气质。文字若出现，应像设计展览信息一样参与构图：少量超大标题分散在上方或边缘形成静态重心，细小说明文字用窄行距、短段落和精确对齐建立阅读节奏，深色字保持克制、锐利、留足呼吸空间。构图避免把元素填满，保留明显的空白停顿、边缘裁切的色雾、微小符号或标记作为节拍，使主题内容像被柔光照亮的抽象记忆，而非普通装饰背景。\n主题：夏日治愈 日签 2026-06-30 再见6月 / 用途：朋友圈分享 / 信息点，有趣的点至少五个 / 比例9:10",
      "gen_prompt": "Create a visual design centered on diffused glow and informational white space for any theme. The theme is first translated into 2-3 large, soft-edged translucent color mists that overlap, interpenetrate and slightly offset in the mid-frame, forming a halo-like main visual rather than a hard-outlined illustration; one mist carries the strongest emotional energy (largest, most saturated), another guides the flow direction, a third is only a faint air-tone, so the visual slowly emerges from large white space. Background stays high-brightness, airy, clean, with soft paper grain like fine print noise across the whole frame, but never dirty, aged or yellowed. Colors are extracted from the theme's material/season/brand/mood, mapped to a bright base, an emotional main color, warm-cool supports, a little crisp accent, and dark info text; keep a large light base, a little high-saturation glow, soft transitions and clean color steps so the whole feels bright, airy, dreamy but orderly. Any text participates in the composition like exhibition info: a few oversized titles scattered at top or edges as static weight, tiny captions with narrow leading, short paragraphs and precise alignment, dark text restrained, sharp, with breathing space. Avoid filling elements; keep clear white pauses, edge-cropped color mist, tiny symbols/marks as beats, so the theme reads like an abstract memory lit by soft glow, not an ordinary decorative background. ALL TEXT IN ENGLISH. Theme: Summer Healing Daily Sign 2026-07-01, \"Hello July, be kind to me\". Purpose: social moments card. At least five interesting info points. Ratio 9:10.",
      "prompt_ko": "확산 광감과 정보 여백을 핵심으로 한 비주얼 디자인(임의 테마). 테마를 먼저 2~3개의 크고 가장자리 부드러운 반투명 색안개로 변환, 화면 중단에서 겹치고 교차·약간 어긋나 광륜이 번지는 듯한 메인 비주얼(선명한 외곽 일러스트 아님). 한 덩이는 가장 강한 정서 에너지(최대·최고 채도), 다른 덩이는 흐름 방향 보조, 셋째는 옅은 공기 바탕색 → 넓은 여백에서 서서히 드러남. 배경은 고명도·맑음·깨끗, 통풍감+부드러운 종이 그레인(전면 미세 인쇄 노이즈, 단 더러움/낡음/누런빛 금지). 색은 테마의 재질·계절·브랜드·정서에서 추출 → 밝은 바탕·정서 주색·한난 보조색·소량 강조색·짙은 정보 텍스트. 넓은 라이트 바탕+소량 고채도 발광색+부드러운 그라데이션+깨끗한 색계조 → 밝고 경쾌·몽환적이되 질서. 텍스트는 전시 정보처럼 구성 참여: 소량 초대형 타이틀을 상단/가장자리에 분산(정적 무게중심), 작은 설명문은 좁은 행간·짧은 단락·정확 정렬, 짙은 글자는 절제·날카로움·여백. 요소 꽉 채우지 말 것, 명확한 여백 멈춤·가장자리 잘린 색안개·작은 기호를 박자로. ※원문 중국어 텍스트 → 영어로 생성. 테마: 여름 힐링 데일리사인 / 용도: SNS 공유 카드 / 정보점 최소 5개 / 비율 9:10.",
      "ref_image": null,
      "result": "results/xxd-daily-1.png",
      "seed": 133411685
    },
    {
      "id": "chillai-1",
      "source": "https://x.com/ChillaiKalan__/status/2071616450943656065",
      "author": "@ChillaiKalan__",
      "date": "2026-06-30",
      "lang": "en",
      "target_model": "GPT Image 2 (SocialSight)",
      "category": "스포츠 포스터",
      "title": "FIFA 월드컵 스타일 축구선수 에디토리얼 포스터",
      "prompt": "Create a premium sports editorial poster in a modern FIFA World Cup campaign style. The composition features a full-body professional football player standing confidently in the center with arms stretched wide in a victory pose, looking slightly upward with a determined expression. Behind the player is an oversized bold white jersey number occupying most of the background, creating a striking layered composition. The background is a solid national team color with a subtle textured grain finish (red for Portugal, yellow for Brazil, or matching any selected team). The player stands in front of the giant number with realistic shadows and perfect depth separation.\nPlace the player's surname in a clean futuristic geometric font at the top-left, while the national team crest is positioned at the top-right. At the bottom-left, display the jersey number in oversized bold typography followed by a period (e.g., \"7.\" or \"10.\"). At the bottom-right, add compact editorial information including tournament title, national team, player position, captain designation (if applicable), and a stylish barcode graphic separated by a thin vertical accent line.\nMaintain a minimal, luxury editorial aesthetic with perfect alignment, generous negative space, crisp typography, and premium sports branding. Use ultra-realistic lighting, sharp jersey details, visible fabric texture, natural skin tones, realistic shadows, high contrast, and cinematic color grading. The design should resemble an official World Cup player campaign poster created by a top sports creative agency.\nStyle: Modern editorial, sports branding, premium poster, minimalist graphic design, clean typography, geometric layout, bold oversized number, ultra-realistic, photorealistic, commercial quality, high-end sports advertisement, 8K, HDR, razor-sharp details, magazine cover aesthetic.",
      "prompt_ko": "모던 FIFA 월드컵 캠페인 스타일의 프리미엄 스포츠 에디토리얼 포스터. 전신 프로 축구선수가 중앙에 자신감 있게 양팔 벌린 승리 포즈, 약간 위 응시 결연한 표정. 뒤에 거대한 볼드 흰색 등번호가 배경 대부분 차지(레이어드 구성). 배경은 국가대표 단색(포르투갈 빨강·브라질 노랑 등)+미세 그레인. 선수는 거대 숫자 앞, 사실적 그림자+완벽한 깊이 분리. 좌상단 선수 성(姓) 깔끔한 퓨처리스틱 기하 폰트, 우상단 국가대표 크레스트. 좌하단 거대 볼드 등번호+마침표(\"7.\" \"10.\"). 우하단 컴팩트 정보(대회명·국가·포지션·주장 표시·세련된 바코드, 가는 세로 액센트선 구분). 미니멀·럭셔리 에디토리얼, 완벽 정렬, 넉넉한 여백, 선명 타이포, 프리미엄 스포츠 브랜딩. 초사실 조명·선명 저지 디테일·천 질감·자연 피부톤·사실 그림자·고대비·시네마틱 그레이딩. 톱 스포츠 에이전시의 공식 월드컵 캠페인 포스터처럼. 8K·HDR·초선명·매거진 커버 미학.",
      "ref_image": null,
      "result": "results/chillai-1.png",
      "seed": 863178330
    },
    {
      "id": "shima-1",
      "source": "https://x.com/shi_ma_ya_su/status/2071710398978670791",
      "author": "@shi_ma_ya_su",
      "date": "2026-06-30",
      "lang": "ja",
      "target_model": "생성AI 범용",
      "category": "배너 디자인",
      "title": "과일 타르트 배너 — 분위기형(CTA 없음)",
      "prompt": "テーマ：季節の果実とご褒美時間を感じさせる / 狙い：世界観や空気感を伝えて、印象を残すデザイン\n▼プロンプト：フルーツタルトのバナーを1080×1080で作って\nルール\n- 「やさしく味わいたい」と思える、短く上品なメインコピー\n- 季節感のあるやわらかな配色で、余白のある上質なポスター風にする\n- いちご、キウイ、オレンジ、ブルーベリーなどのフルーツ、やわらかなクリーム、焼き色のきれいなタルト生地、白い皿や布を使う\n- フルーツの香りや季節の空気感、ご褒美時間が静かに伝わる構成にする\n- 光沢、発光、金文字、赤いCTA、強いコントラストは使わない\n- 文字要素はメインコピー、サブコピーの2つまで（サブコピーは1行、15文字以内）\n- 小さい文字、注釈、価格、日付、ダミーテキストは入れない\n- CTAボタンや購入を促す文言は入れない",
      "gen_prompt": "Create a fruit tart banner, 1080x1080. Theme: seasonal fruit and a rewarding moment. Goal: convey a worldview/atmosphere and leave an impression.\nRules:\n- a short, elegant ENGLISH main copy that feels like \"savor it gently\"\n- soft seasonal color palette, an upscale poster look with generous white space\n- use strawberry, kiwi, orange, blueberry, soft cream, a beautifully baked tart crust, a white plate/cloth\n- composition quietly conveys fruit aroma, seasonal air, reward time\n- no gloss, glow, gold text, red CTA, or strong contrast\n- at most 2 text elements (main copy + sub copy); sub copy one short line\n- no tiny text, annotations, prices, dates, or dummy text\n- NO CTA button or purchase-prompting words\n- fonts/weights match the overall taste. ALL TEXT IN ENGLISH.",
      "prompt_ko": "과일 타르트 배너 1080×1080. 테마: 계절 과일과 보상 시간. 의도: 세계관·분위기 전달, 인상 남기기.\n규칙: '부드럽게 음미하고 싶은' 짧고 우아한 메인카피 / 계절감 부드러운 배색, 여백 있는 고급 포스터풍 / 딸기·키위·오렌지·블루베리 등 과일, 부드러운 크림, 구움색 예쁜 타르트, 흰 접시·천 / 과일 향·계절 공기·보상 시간 조용히 전달 / 광택·발광·금문자·빨간 CTA·강한 대비 금지 / 텍스트 메인+서브 2개까지(서브 1행 짧게) / 작은 글씨·주석·가격·날짜·더미 금지 / **CTA버튼·구매유도 문구 금지**. ※일본어 카피 → 영어로 생성.",
      "ref_image": null,
      "result": "results/shima-1.png",
      "seed": 1984370786
    },
    {
      "id": "shima-2",
      "source": "https://x.com/shi_ma_ya_su/status/2071710398978670791",
      "author": "@shi_ma_ya_su",
      "date": "2026-06-30",
      "lang": "ja",
      "target_model": "생성AI 범용",
      "category": "배너 디자인",
      "title": "과일 타르트 배너 — 행동유도형(CTA 있음)",
      "prompt": "テーマ：華やかさとおいしさを伝えて、行動を促す / 狙い：商品の魅力をわかりやすく伝えて、食べたい気持ちを高め、行動につなげるデザイン\n▼プロンプト：フルーツタルトのバナーを1080×1080で作って\nルール\n- 「今すぐ食べたい」と思える、短く上品なメインコピー\n- 明るく上品で、SNSでも目を引く配色にする\n- いちご、キウイ、オレンジ、ブルーベリーなどのフルーツ、つやのあるクリーム、こんがり焼けたタルト生地を使う\n- フルーツのみずみずしさ、甘さ、華やかさ、ご褒美感がひと目で伝わる構成にする\n- 光沢、発光、金文字、赤いCTA、強いコントラストは使わない\n- 文字要素はメインコピー、サブコピー、CTAの3つまで（サブコピーは1行、15文字以内）\n- 小さい文字、注釈、価格、日付、ダミーテキストは入れない\n- CTAボタンを設置し、次の行動がひと目でわかるようにする",
      "gen_prompt": "Create a fruit tart banner, 1080x1080. Theme: convey glamour and deliciousness, drive action. Goal: clearly convey product appeal, raise the urge to eat, lead to action.\nRules:\n- a short, elegant ENGLISH main copy that feels like \"want to eat it now\"\n- bright, elegant, eye-catching palette for social media\n- use strawberry, kiwi, orange, blueberry, glossy cream, a golden-baked tart crust\n- composition conveys juiciness, sweetness, glamour, reward at a glance\n- no gloss, glow, gold text, red CTA, or strong contrast\n- at most 3 text elements (main copy + sub copy + CTA); sub copy one short line\n- no tiny text, annotations, prices, dates, dummy text\n- PLACE a CTA button so the next action is clear at a glance\n- fonts/weights match the overall taste. ALL TEXT IN ENGLISH.",
      "prompt_ko": "과일 타르트 배너 1080×1080. 테마: 화려함·맛 전달, 행동 유도. 의도: 상품 매력 전달, 먹고 싶은 마음 높여 행동 연결.\n규칙: '지금 먹고 싶은' 짧고 우아한 메인카피 / 밝고 우아, SNS에서 눈길 끄는 배색 / 딸기·키위·오렌지·블루베리, 윤기 크림, 노릇 타르트 / 과일 싱싱함·단맛·화려함·보상감 한눈에 / 광택·발광·금문자·빨간 CTA·강대비 금지 / 텍스트 메인+서브+CTA 3개까지(서브 1행) / 작은글씨·주석·가격·날짜·더미 금지 / **CTA버튼 설치, 다음 행동 한눈에**. ※일본어 카피 → 영어로 생성.",
      "ref_image": null,
      "result": "results/shima-2.png",
      "seed": 500613899
    },
    {
      "id": "krypt-1",
      "source": "https://x.com/0x00_Krypt/status/2071556293681435067",
      "author": "@0x00_Krypt",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT Image 2 / Banana",
      "category": "아트 포스터",
      "title": "포스트인상주의 금붕어 유화 포스터 (Flora & Reverie)",
      "prompt": "A flat illustration poster in post-impressionist style. White background with generous white space. All text is left-aligned.\n[LAYOUT — TOP BAR] At the very top, a single line with three items in the same small serif font: \"2026\" flush left, \"POSTER DESIGN\" centered, \"2026\" flush right. Smallest readable font size.\n[LAYOUT — LEFT COLUMN, TOP TO BOTTOM]\n1. Series name in large display serif font, two lines, left-aligned, black: Flora & Reverie\n2. Chinese title in small-weight Song typeface (宋体), slightly smaller: 金鳞戏水 (render correctly as Han characters)\n3. English subtitle in the same fine serif, one size smaller: Goldfish, Golden Scales in Still Water\n[LAYOUT — BOTTOM]\n4. At the very bottom left, a Chinese tagline in tiny Song typeface: 一尾金鳞游，闲散胜浮生\n5. Below it, the smallest font size, a multi-line English paragraph, left-aligned: The goldfish moves as if time were optional. Its fins trail behind like silk left in a current — unhurried, untroubled, ornamental in the oldest sense of the word. To watch one is to practice a kind of forgetting. Whatever you carried in, the water takes.\n[ILLUSTRATION STYLE] The main illustration fills the right half and center, bleeding slightly off the right and top edges. Subject: two goldfish — one large, one small — swimming among trailing aquatic grasses, with a few small rising air bubbles. Painting style: post-impressionist, plein-air watercolor-oil hybrid. Loose, gestural brushstrokes with visible paint texture. Goldfish bodies in luminous amber gold and vermillion orange, translucent fins in thin layered washes — fin edges almost dissolving into the white background. Aquatic grass in loose upward strokes of olive green and pale jade. Background pure white — no water explicitly painted, only implied by plants, bubbles, and the fish's orientation.\n[COMPOSITION] The larger goldfish curves in a gentle arc through the center-right, tail flowing down and left. The smaller goldfish lower, facing the opposite direction — a classic yin-yang pairing. Aquatic grass rises from the bottom edge into the upper third. Three or four small circular bubbles float upward near the larger fish. Generous white space in the upper-left quadrant.\n[COLOR] The goldfish are the sole warm-toned elements — amber-vermillion bodies glow against the white. Everything else cool or neutral: olive grass, blue-gray bubble outlines, faint gray-green shadows beneath the fish for depth. Palette like Song dynasty ceramic glaze — restrained warmth against cool white.\n[OVERALL] The text portion (left side) has a clean white background — no illustration overlaps the text. The whole piece feels like a quiet nature journal elevated to editorial design. Aspect ratio: 3:4 (portrait). No borders or frames.",
      "gen_prompt": "A flat illustration poster in post-impressionist style. White background with generous white space. All text is left-aligned.\n[LAYOUT — TOP BAR] At the very top, a single line with three items in the same small serif font: \"2026\" flush left, \"POSTER DESIGN\" centered, \"2026\" flush right. Smallest readable font size.\n[LAYOUT — LEFT COLUMN, TOP TO BOTTOM]\n1. Series name in large display serif font, two lines, left-aligned, black: Flora & Reverie\n2. Title in an elegant English serif, slightly smaller: \"Golden Scales\"\n3. English subtitle in the same fine serif, one size smaller: Goldfish, Golden Scales in Still Water\n[LAYOUT — BOTTOM]\n4. At the very bottom left, an English tagline in tiny serif: \"A lone golden fish drifts free, idleness outshining the floating world\"\n5. Below it, the smallest font size, a multi-line English paragraph, left-aligned: The goldfish moves as if time were optional. Its fins trail behind like silk left in a current — unhurried, untroubled, ornamental in the oldest sense of the word. To watch one is to practice a kind of forgetting. Whatever you carried in, the water takes.\n[ILLUSTRATION STYLE] The main illustration fills the right half and center, bleeding slightly off the right and top edges. Subject: two goldfish — one large, one small — swimming among trailing aquatic grasses, with a few small rising air bubbles. Painting style: post-impressionist, plein-air watercolor-oil hybrid. Loose, gestural brushstrokes with visible paint texture. Goldfish bodies in luminous amber gold and vermillion orange, translucent fins in thin layered washes — fin edges almost dissolving into the white background. Aquatic grass in loose upward strokes of olive green and pale jade. Background pure white — no water explicitly painted, only implied by plants, bubbles, and the fish's orientation.\n[COMPOSITION] The larger goldfish curves in a gentle arc through the center-right, tail flowing down and left. The smaller goldfish lower, facing the opposite direction — a classic yin-yang pairing. Aquatic grass rises from the bottom edge into the upper third. Three or four small circular bubbles float upward near the larger fish. Generous white space in the upper-left quadrant.\n[COLOR] The goldfish are the sole warm-toned elements — amber-vermillion bodies glow against the white. Everything else cool or neutral: olive grass, blue-gray bubble outlines, faint gray-green shadows beneath the fish for depth. Palette like Song dynasty ceramic glaze — restrained warmth against cool white.\n[OVERALL] The text portion (left side) has a clean white background — no illustration overlaps the text. The whole piece feels like a quiet nature journal elevated to editorial design. Aspect ratio: 3:4 (portrait). No borders or frames. | All visible text/typography in ENGLISH only.",
      "prompt_ko": "포스트인상주의 스타일 플랫 일러스트 포스터. 흰 배경+넉넉한 여백, 모든 텍스트 좌측 정렬.\n[상단바] 맨 위 한 줄에 같은 작은 세리프로 3항목: \"2026\"(좌)·\"POSTER DESIGN\"(중)·\"2026\"(우), 최소 가독 크기.\n[좌측 컬럼 위→아래] 1.시리즈명 큰 디스플레이 세리프 2줄: Flora & Reverie / 2.중국어 타이틀(송체) 약간 작게: 金鳞戏水 / 3.영어 부제: Goldfish, Golden Scales in Still Water\n[하단] 4.좌하단 작은 송체 중국어 태그라인: 一尾金鳞游，闲散胜浮生 / 5.그 아래 최소 크기 영어 다단락: 금붕어가 시간이 선택사항인 듯 헤엄친다… (시적 문구)\n[일러스트] 우측 절반+중앙 채움, 우/상단 살짝 블리드. 금붕어 2마리(대·소)가 수초 사이 헤엄, 작은 기포 몇 개. 포스트인상주의 플레네르 수채-유화 하이브리드, 느슨한 제스처 붓터치+가시적 페인트 질감. 금붕어=호박금·주홍, 반투명 지느러미는 얇은 워시(가장자리가 흰 배경에 녹아듦). 수초=올리브그린·페일제이드 상승 스트로크. 배경 순백(물 직접 안 그림, 식물·기포·물고기 방향으로 암시).\n[구성] 큰 금붕어가 중앙우측을 완만한 호로, 꼬리 좌하향. 작은 금붕어는 아래, 반대 방향(음양 쌍). 수초 하단→상단 1/3. 기포 3~4개. 좌상단 넉넉한 여백.\n[색] 금붕어만 따뜻한 색(호박-주홍 발광), 나머지 차갑/중성(올리브 수초·청회 기포선·옅은 회녹 그림자). 송대 도자 유약 같은 절제된 따뜻함 vs 차가운 흰색.\n[전체] 좌측 텍스트 영역은 깨끗한 흰 배경(일러스트 안 겹침). 조용한 자연 저널을 에디토리얼로 승화. 종횡비 3:4, 테두리/프레임 없음. ※중국어 타이틀 2개 → 영어로 생성.",
      "ref_image": null,
      "result": "results/krypt-1.png",
      "seed": 1081629180
    },
    {
      "id": "lucia3-1",
      "source": "https://x.com/luciaverseai/status/2071659917229097406",
      "author": "@luciaverseai",
      "date": "2026-06-30",
      "lang": "en",
      "target_model": "범용",
      "category": "콜라주/9그리드",
      "title": "플랫폼별 9그리드 포스터 (동일 인물, FB/IG/TikTok 등)",
      "prompt": "Create a high-quality 3x3 grid of nine cinematic AI posters featuring the same stylish blonde woman wearing sunglasses as the central character. Each panel represents a different platform—Facebook, Instagram, TikTok, YouTube, WhatsApp, ChatGPT, Threads, Snapchat, and LinkedIn—with its own signature color palette, matching fashionable outfit, and immersive themed background filled with glowing logos, holographic UI elements, and platform-specific icons. Maintain a consistent character, ultra-detailed photorealistic style, vibrant lighting, futuristic aesthetics, and clean poster composition across all nine panels.",
      "prompt_ko": "동일한 세련된 금발 여성(선글라스)을 중심 캐릭터로 한 9개 시네마틱 AI 포스터의 3×3 그리드. 각 패널은 다른 플랫폼(Facebook·Instagram·TikTok·YouTube·WhatsApp·ChatGPT·Threads·Snapchat·LinkedIn)을 나타내며, 각자의 시그니처 색팔레트·어울리는 패셔너블 의상·발광 로고와 홀로그래픽 UI 요소·플랫폼별 아이콘으로 채운 몰입형 테마 배경. 9패널 전체에 일관된 캐릭터·초디테일 포토리얼·생생한 조명·퓨처리스틱 미학·깔끔한 포스터 구성 유지.",
      "ref_image": null,
      "result": "results/lucia3-1.png",
      "seed": 1914998904
    },
    {
      "id": "gdgtify-3",
      "source": "https://x.com/Gdgtify/status/2071776988436562115",
      "author": "@Gdgtify",
      "date": "2026-06-30",
      "lang": "en",
      "target_model": "Midjourney/범용",
      "category": "데이터viz/플랫레이",
      "title": "빈도 밀도 플랫레이 (흔할수록 군집, 희귀할수록 고립)",
      "prompt": "2x2 grid, AI inferred topics, 16:9. A top-down flat-lay where [THEME] objects are packed by real-world frequency, the most common swarming densely on one side and the rarest standing alone with open space on the other, the density distribution forming the silhouette of [SHAPE] ::5 Frequency Logic: AI_INFER 40-60 themed objects ranked by true rarity or commonness, packed so visual density directly encodes frequency — abundance reads as crowding, rarity as isolation — the density gradient legible at a glance ::5 Composition: Density-graded packing, smooth crowd-to-sparse transition, clean silhouette edge, generous margin ::3 Material Physics: Real themed objects, accurate materials, consistent matte finish, soft shadows ::2 Illumination: Flat overhead softbox, no glare ::2 Typography: Tiny frequency labels along the lower edge ::2 Render Stack: Density-map flat-lay, frequency-packed collection, data-viz arrangement, 8k ::1 Negative: [uniform spacing, mismatched density, broken silhouette, total overlap, tilt, 3d perspective, hands] ::-1",
      "gen_prompt": "2x2 grid, AI inferred topics, 16:9. A top-down flat-lay where [THEME] objects are packed by real-world frequency, the most common swarming densely on one side and the rarest standing alone with open space on the other, the density distribution forming the silhouette of [SHAPE] Frequency Logic: AI_INFER 40-60 themed objects ranked by true rarity or commonness, packed so visual density directly encodes frequency — abundance reads as crowding, rarity as isolation — the density gradient legible at a glance Composition: Density-graded packing, smooth crowd-to-sparse transition, clean silhouette edge, generous margin Material Physics: Real themed objects, accurate materials, consistent matte finish, soft shadows Illumination: Flat overhead softbox, no glare Typography: Tiny frequency labels along the lower edge Render Stack: Density-map flat-lay, frequency-packed collection, data-viz arrangement, 8k Negative: [uniform spacing, mismatched density, broken silhouette, total overlap, tilt, 3d perspective, hands]",
      "prompt_ko": "2×2 그리드, AI 추론 토픽, 16:9. [테마] 오브젝트를 실제 빈도순으로 배치한 탑다운 플랫레이 — 가장 흔한 것은 한쪽에 빽빽이 군집, 가장 희귀한 것은 반대편에 여백 두고 홀로. 밀도 분포가 [형태] 실루엣을 이룸. 40~60개를 희귀도순 랭크, 시각 밀도가 빈도를 직접 인코딩(풍부=군집, 희귀=고립). 밀도 등급 패킹, 군집→희소 부드러운 전환, 깔끔 실루엣, 여백. 실제 오브젝트·정확 재질·일관 매트·부드러운 그림자. 오버헤드 소프트박스. 하단 작은 빈도 라벨. 8k. ※::N(MJ 가중치) 제거.",
      "ref_image": null,
      "result": "results/gdgtify-3.png",
      "seed": 149218326
    },
    {
      "id": "gdgtify-4",
      "source": "https://x.com/Gdgtify/status/2070152031243841965",
      "author": "@Gdgtify",
      "date": "2026-06-25",
      "lang": "en",
      "target_model": "Midjourney/범용",
      "category": "데이터viz/플랫레이",
      "title": "진화 타임라인 knolling (연대순 진화)",
      "prompt": "2x2 grid, do this for 4 AI inferred themes, 16:9. A top-down knolling flat-lay where [THEME] objects are arranged in strict chronological order from [ERA START] on the left to [ERA END] on the right, the full timeline together forming the silhouette of [SHAPE] ::5 Time Logic: AI_INFER 30-40 themed objects that visibly evolve across eras — earliest/most worn at the start, newest/most modern at the end — sequence carrying the story, outline carrying the meaning ::5 Composition: Strict left-to-right grid, even temporal spacing, clean silhouette edge, generous margin ::3 Material Physics: Real objects, era-accurate materials and wear, consistent matte finish, soft shadows ::2 Illumination: Flat overhead softbox, no glare ::2 Typography: Small era labels along the lower edge ::2 Render Stack: Knolling-meets-timeline, evolutionary flat-lay, chronological collection, 8k ::1 Negative: [scrambled chronology, broken silhouette, overlap, tilt, anachronistic clutter, 3d perspective, hands] ::-1",
      "gen_prompt": "2x2 grid, do this for 4 AI inferred themes, 16:9. A top-down knolling flat-lay where [THEME] objects are arranged in strict chronological order from [ERA START] on the left to [ERA END] on the right, the full timeline together forming the silhouette of [SHAPE] Time Logic: AI_INFER 30-40 themed objects that visibly evolve across eras — earliest/most worn at the start, newest/most modern at the end — sequence carrying the story, outline carrying the meaning Composition: Strict left-to-right grid, even temporal spacing, clean silhouette edge, generous margin Material Physics: Real objects, era-accurate materials and wear, consistent matte finish, soft shadows Illumination: Flat overhead softbox, no glare Typography: Small era labels along the lower edge Render Stack: Knolling-meets-timeline, evolutionary flat-lay, chronological collection, 8k Negative: [scrambled chronology, broken silhouette, overlap, tilt, anachronistic clutter, 3d perspective, hands]",
      "prompt_ko": "2×2 그리드(4개 AI 추론 테마), 16:9. [테마] 오브젝트를 [시대시작]→[시대끝] 엄격한 연대순 배치 탑다운 knolling 플랫레이, 전체 타임라인이 [형태] 실루엣. 30~40개가 시대별 가시적 진화(오래된/낡은 것 시작, 최신/모던 끝), 순서=스토리·외곽=의미. 좌→우 그리드, 균등 시간 간격, 깔끔 실루엣, 여백. 시대 정확 재질·마모, 일관 매트. 오버헤드 소프트박스. 하단 작은 시대 라벨. 8k. ※::N 제거.",
      "ref_image": null,
      "result": "results/gdgtify-4.png",
      "seed": 329305969
    },
    {
      "id": "shz-2",
      "source": "https://x.com/sha_zdiii/status/2071449663841218819",
      "author": "@sha_zdiii",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT Image 2",
      "category": "제품 광고",
      "title": "럭셔리 웰니스 디톡스 음료 광고 (인포그래픽)",
      "prompt": "Minimalist luxury wellness poster design, ultra-realistic healthy detox drink advertisement, clean white marble background, soft natural lighting, premium editorial aesthetic, two transparent glass bottles centered, one bottle filled with layered fresh ingredients ([fruit/vegetables visible in clean sections]), second bottle filled with blended smoothie matching ingredient colors, elegant black serif typography at top saying \"DRINK FOR [BENEFIT NAME]\", thin clean infographic lines pointing to ingredients on left, benefit text box on right with [4 key health benefits], beautiful glowing female model beside bottles, natural skin texture, soft makeup, healthy radiant face, calm pose, luxury skincare-commercial vibe, fresh ingredients placed around bottom for realism, clean composition, balanced spacing, modern Instagram viral health post, photorealistic, high-detail, premium branding aesthetic, soft shadows, crisp reflections, highly detailed glass texture, [viral Instagram wellness ad style], [Pinterest aesthetic], [premium health brand campaign], 4K ultra HD, sharp focus, cinematic realism.",
      "prompt_ko": "미니멀 럭셔리 웰니스 포스터, 초사실 건강 디톡스 음료 광고. 깨끗한 흰 대리석 배경, 부드러운 자연광, 프리미엄 에디토리얼. 중앙에 투명 유리병 2개(하나=레이어드 신선 재료 [과일/채소 단면], 하나=재료색 매칭 블렌디드 스무디). 상단 우아한 블랙 세리프 \"DRINK FOR [효능명]\". 좌측 가는 인포그래픽 라인이 재료 지시, 우측 효능 박스 [핵심 효능 4개]. 병 옆 빛나는 여성 모델(자연 피부결·소프트 메이크업·건강 광채·차분 포즈). 하단 신선 재료 배치. 깔끔 구성·균형 여백·바이럴 인스타 헬스 포스트·포토리얼·4K.",
      "ref_image": null,
      "result": "results/shz-2.png",
      "seed": 585720201
    },
    {
      "id": "delulu-2",
      "source": "https://x.com/MissDelulu9/status/2071826733184295243",
      "author": "@MissDelulu9",
      "date": "2026-06-30",
      "lang": "en",
      "target_model": "GPT IMAGE 2",
      "category": "여행 포스터",
      "title": "도시별 미니멀 플랫벡터 여행 포스터 (일본 문구류풍)",
      "prompt": "Premium minimal flat-vector travel poster for [CITY_NAME], 3:4 vertical. Create a fresh, elegant city-specific travel illustration with the city's iconic landmark as the main focus, plus local transport, everyday lifestyle moment, native nature detail, and unique composition. Japanese stationery aesthetic, luxury sticker illustration, clean thin outlines, flat colors, soft minimal shapes. Place [CITY_NAME] in the upper-left with premium typography and a short refined caption. Use only 3-6 small natural figures doing city-specific activities. Palette: powder blue, sky blue, cream, beige, sage green with tiny blush accents. Calm, airy, high-end postcard style. No realism, no watercolor, no gradients, no heavy shading, no crowded scene, no generic tourist collage, no repeated layouts.",
      "prompt_ko": "[도시명]을 위한 프리미엄 미니멀 플랫벡터 여행 포스터, 3:4 세로. 도시 상징 랜드마크를 메인으로 + 현지 교통·일상 라이프스타일 순간·토착 자연 디테일·독특한 구성. 일본 문구류 미학, 럭셔리 스티커 일러스트, 깔끔한 가는 외곽선, 플랫 컬러, 부드러운 미니멀 형태. 좌상단에 [도시명] 프리미엄 타이포 + 짧은 세련된 캡션. 도시 특화 활동하는 작은 인물 3~6명만. 팔레트: 파우더블루·스카이블루·크림·베이지·세이지그린+작은 블러시. 차분·에어리·하이엔드 엽서풍. 사실주의·수채·그라데이션·무거운 셰이딩·붐비는 장면·일반 관광 콜라주·반복 레이아웃 금지.",
      "ref_image": null,
      "result": "results/delulu-2.png",
      "seed": 2024928810
    },
    {
      "id": "yang-3",
      "source": "https://x.com/YangOnchain/status/2071805624434970825",
      "author": "@YangOnchain",
      "date": "2026-06-30",
      "lang": "zh",
      "target_model": "GPT image 2",
      "category": "장치/전시 포스터",
      "title": "부유 원판 장치 포스터 (悬浮圆片, 전시 비주얼)",
      "prompt": "请生成一张竖版 3:4 的中文成品海报。参考\"悬浮圆片装置空间\"的视觉逻辑：大量圆形、椭圆形薄片悬挂在高挑空间中，层层漂浮，具有强烈的空间纵深、重复节奏和装置艺术感。但不要简单复刻原图，要做大幅度魔改与再设计。保留\"悬浮圆片/层叠漂浮/空间包裹感\"的核心，同时在主题概念、材质语言、光影氛围、色彩系统、构图、排版上明显重构。【主题】方向{填写}/主标题{填写}/副标题{可空}。画面：大量漂浮圆片/圆盘/半透明薄片/发光介质，形成空间结构与节奏，沉浸·包裹·悬浮感；场景可设为未来展览/梦境/月相装置/数据界面/声音共振场/微观生态/记忆切片/光学实验场/时间样本库；必须有海报感；构图大胆(俯视/仰视/中心透视/偏轴/留白/裁切)；材质变化(金属/半透膜/玻璃/纸/雾面亚克力/发光薄膜/镜面/纤维)；光影有情绪。版式：完整中文排版成品，标题有设计感，可少量英文，含展览信息/地点/说明小字，不写具体旧年份，排版与画面融合，高级克制干净。关键词：极简展览海报·装置艺术·当代设计海报·留白·材质对比·沉浸。不要水印/Logo/乱码/廉价电商感。",
      "gen_prompt": "Create a vertical 3:4 finished poster with completed typography. Reference the visual logic of a \"floating disc installation space\": many circular/elliptical thin discs suspended in a tall space, layered and floating, with strong spatial depth, repetitive rhythm and installation-art feel. Do not simply replicate — heavily remix and redesign. Keep the core (floating discs / layered floating / spatial envelopment) while clearly restructuring theme concept, material language, light/shadow mood, color system, composition and typography into a brand-new poster.\n[THEME] direction: {theme}; Main title: {title}; Subtitle: {optional}.\nRequirements: main subject = many floating discs / plates / translucent thin sheets / glowing media / material units forming clear spatial structure and rhythm, immersive, enveloping, floating; the scene can be reset as a future exhibition, dream space, lunar-phase installation, data interface, sound-resonance field, microscopic ecology, memory slices, optical lab, or time-sample archive; it must read as a POSTER, not a mere render; bold composition allowed (top-down, look-up, central perspective, off-axis, negative-space, partial crop); emphasize material variation (metal, translucent film, glass, paper, matte acrylic, glowing film, mirror, fiber); light/shadow with emotion (dreamy, restrained, mysterious, futuristic, quiet, experimental).\nLayout: a complete finished poster with clear, designed title typography; minor supporting info allowed but ALL TEXT IN ENGLISH; exhibition info, location and captions as small text like a real exhibition poster; do not write specific old years; typography fused with the image, not stiffly pasted; high-end, restrained, clean, with an art/design-exhibition vibe.\nStyle keywords: minimal exhibition poster, installation-art visual, contemporary design poster, spatial installation, artful, negative space, material contrast, immersive atmosphere. No watermark, no logo, no garbled text, no cheap e-commerce feel.",
      "prompt_ko": "세로 3:4 완성 포스터. '부유 원판 장치 공간' 시각 로직 참고: 원형·타원 박편 다수가 높은 공간에 매달려 층층이 부유, 강한 공간 종심·반복 리듬·설치미술감. 단순 복제 말고 대폭 변형·재설계. 핵심(부유 원판/층층 부유/공간 포위감) 유지하되 주제·재질·광영·색·구도·타이포 재구성. [주제]방향{}/주제목{}/부제{선택}. 화면: 부유 원판/원반/반투명 박편/발광 매질 다수가 공간 구조·리듬 형성, 몰입·포위·부유감; 장면=미래전시/꿈/월상장치/데이터인터페이스/음향공명장/미시생태/기억절편/광학실험장/시간샘플고; 포스터감 필수; 대담 구도(부감/앙각/중심투시/편축/여백/크롭); 재질 변화(금속/반투막/유리/종이/무광아크릴/발광막/거울/섬유); 광영 정서(몽환·절제·신비·미래·고요·실험). 버전: 완성 타이포, 디자인된 타이틀, 소량 보조정보, 전시정보/장소/설명 소자, 구체 옛 연도 금지, 타이포-화면 융합, 고급·절제·깨끗·전시 포스터 기질. ※원문 중국어 위주 → 영어 텍스트로 생성.",
      "ref_image": null,
      "result": "results/yang-3.png",
      "seed": 441260753
    },
    {
      "id": "larus-2",
      "source": "https://x.com/MrLarus/status/2070858409193214245",
      "author": "@MrLarus",
      "date": "2026-06-27",
      "lang": "en",
      "target_model": "ChatGPT-Image2",
      "category": "스토리보드/콘티",
      "title": "초와이드 연속 스토리보드 (3:1, 동선+타임라인)",
      "prompt": "Generate a single complete image of an [Ultra-Wide Short Drama Scene Storyboard], one full picture, horizontal 3:1 format, no collages, no multi-grids, no divided columns.\nTheme: [scene, e.g. street chase battle / hotel corridor ambush / subway station escape / night market street conflict]\nThe visuals are not an ordinary poster or traditional storyboard panels, but a \"continuous background + multi-time-point character freeze-frames + single-direction plot progression + hand-drawn motion line annotations + bottom timeline\" story-space storyboard.\nThe background must be one complete, continuous, realistic scene that unfolds left to right, without cutting into multiple small frames. The plot advances left to right: left = start, middle = conflict escalation, right = ending focal point.\nThe same protagonist and the same pursuer/opponent appear repeatedly in different positions, representing different time points. Keep character clothing, hairstyle and body type consistent. Each subsequent freeze-frame must be further right than the previous, without going back and forth.\nSuggested rhythm: Enter scene -> Get chased close -> Encounter blockade -> First clash -> Conflict escalation -> Counterattack using surroundings -> Escape to the right.\nIncorporate an exquisite hand-drawn marking system: thin hand-drawn arrows, route labels, small circles, brackets, action focus lines, gaze directions, key-node short tags. Keep text minimal, light, refined — like high-end visual notes, not PPT infographics.\nAdd a lightweight timeline at the bottom, e.g. 00:00 Enter / 00:06 Close chase / 00:12 Blockade / 00:18 Clash / 00:26 Escalation / 00:34 Counterattack / 00:42 Escape.\nOverall: a high-end short-drama scheduling storyboard / action plot planning diagram / continuous scene storyboard / story-space map. Key is clarity: where characters come from, where they head, where conflict escalates, where the ending lands.\nAvoid: collages, multi-grids, comic panels, PPT vibe, top/bottom white borders, text-image splits, character path confusion, back-and-forth reversals, discontinuous spaces, oversized characters, excessive text, crude annotations, low resolution.",
      "prompt_ko": "[초와이드 단편드라마 장면 스토리보드] 1장 완성 이미지, 가로 3:1, 콜라주/멀티그리드/분할 금지.\n주제: [장면, 예: 거리 추격전/호텔 복도 매복/지하철 탈출/야시장 충돌]\n일반 포스터·전통 스토리보드 패널이 아니라 '연속 배경 + 다중 시점 인물 정지프레임 + 단방향 플롯 + 손그림 동선 주석 + 하단 타임라인' 스토리 공간 보드.\n배경은 좌→우로 자연스럽게 펼쳐지는 완전 연속 실사 장면(분할 금지). 플롯 좌→우(좌=시작, 중=갈등 고조, 우=결말 초점).\n동일 주인공·동일 추격자가 화면 여러 위치에 반복 등장(다른 시점), 의상·헤어·체형 일관. 각 정지프레임은 이전보다 오른쪽에(역방향 금지).\n리듬: 진입→근접추격→봉쇄→첫충돌→고조→주변활용 반격→우측 탈출.\n정교한 손그림 마킹(가는 화살표·경로 라벨·작은 원·괄호·액션 포커스선·시선 방향·노드 태그), 텍스트 최소·세련(고급 비주얼 노트풍, PPT 아님).\n하단 경량 타임라인(00:00 진입/00:06 추격/00:12 봉쇄/00:18 충돌/00:26 고조/00:34 반격/00:42 탈출).\n전체=고급 단편드라마 스케줄링 스토리보드·액션 플롯 기획도·연속 장면 콘티. 핵심=명료성(인물 동선·갈등·결말). 금지: 콜라주·멀티그리드·만화패널·PPT·흰테두리·텍스트분리·동선혼란·역방향·불연속·과대인물·과도텍스트·조잡주석·저해상.\n※콘티/스토리보드 직결 — storyboard2video 활용 가능.",
      "ref_image": null,
      "result": "results/larus-2.png",
      "seed": 407285625
    },
    {
      "id": "maddox-1",
      "source": "https://x.com/Maddox_Digital/status/2071612693887496353",
      "author": "@Maddox_Digital",
      "date": "2026-06-30",
      "lang": "en",
      "target_model": "GPT-image2/MJ",
      "category": "3D 오브젝트",
      "title": "부유 석회암 3D 프래그먼트 (이끼·산호·수정·야생화)",
      "prompt": "A 3D fragment of rugged limestone floating in mid-air, covered with green moss, pale pink and orange corals, lichen, translucent quartz crystals, wildflowers with light blue petals, clean white background, soft warm natural lighting, photorealistic render, Octane Render, Cinema 4D --ar 3:4 --raw --v 7 --draft",
      "gen_prompt": "A 3D fragment of rugged limestone floating in mid-air, covered with green moss, pale pink and orange corals, lichen, translucent quartz crystals, wildflowers with light blue petals, clean white background, soft warm natural lighting, photorealistic render, Octane Render, Cinema 4D",
      "prompt_ko": "공중에 떠 있는 거친 석회암 3D 프래그먼트, 녹색 이끼·연분홍과 주황 산호·지의류·반투명 석영 결정·연한 파랑 꽃잎 야생화로 덮임, 깨끗한 흰 배경, 부드러운 따뜻한 자연광, 포토리얼 렌더, Octane Render, Cinema 4D. 3:4. ※--ar/--v 등 MJ 파라미터는 생성 시 제거.",
      "ref_image": null,
      "result": "results/maddox-1.png",
      "seed": 63389892
    },
    {
      "id": "zephyra-2",
      "source": "https://x.com/ZephyraLeigh/status/2070777969459737069",
      "author": "@ZephyraLeigh",
      "date": "2026-06-27",
      "lang": "en",
      "target_model": "GPT Image 2",
      "category": "패션 일러스트",
      "title": "럭셔리 패션 일러스트 (에디토리얼 벡터, 템플릿)",
      "prompt": "Create a luxury fashion illustration featuring [PERSON].\nStyle: Modern editorial vector illustration with painterly textures.\nPose: [POSE]\nExpression: [EXPRESSION]\nHair: [HAIRSTYLE]\nOutfit: [OUTFIT]\nAccessories: [Accessory 1] / [Accessory 2] / [Accessory 3]\nHolding: [OBJECT]\nCompanions: [PETS / FLOWERS / OBJECTS]\nBackground: Minimal warm cream background with large negative space.\nArt Style: Minimalist fashion illustration, soft brush textures, flat colors, elegant linework, luxury magazine artwork, premium lifestyle poster, contemporary digital illustration, Pinterest aesthetic, Vogue editorial illustration, 8K.",
      "prompt_ko": "[인물]을 담은 럭셔리 패션 일러스트. 스타일: 페인터리 텍스처의 모던 에디토리얼 벡터 일러스트. 포즈[POSE]/표정[EXPRESSION]/헤어[HAIRSTYLE]/의상[OUTFIT]/액세서리(1·2·3)/들고있는것[OBJECT]/동반(펫·꽃·오브젝트). 배경: 미니멀 따뜻한 크림색+넓은 여백. 아트스타일: 미니멀 패션 일러스트·부드러운 브러시 텍스처·플랫 컬러·우아한 라인워크·럭셔리 매거진·프리미엄 라이프스타일 포스터·핀터레스트·Vogue 에디토리얼·8K.",
      "ref_image": null,
      "result": "results/zephyra-2.png",
      "seed": 1896389613
    },
    {
      "id": "promptlab-2",
      "source": "https://x.com/iamaiistudio/status/2071742565339320451",
      "author": "@iamaiistudio",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT Image 2",
      "category": "제품 광고",
      "title": "네온 에너지드링크 제품 광고 (VOLT RUSH, 시네마틱)",
      "prompt": "Ultra-cinematic product photography of a neon-green energy drink can labeled \"VOLT RUSH\", tilted at a sharp diagonal, bursting through glowing citrus slices and electric sparks. Frozen lime juice splashes and ice shards suspended mid-air, micro droplets clearly visible. High-contrast studio lighting with green neon rim lights, deep dark background, glossy aluminum surface, shallow depth of field, photorealistic, 8K, premium advertising style.",
      "prompt_ko": "네온 그린 에너지드링크 캔(\"VOLT RUSH\" 라벨)의 초시네마틱 제품 사진, 날카로운 대각선 기울기, 빛나는 시트러스 슬라이스와 전기 스파크를 뚫고 나옴. 얼어붙은 라임주스 스플래시와 얼음 파편 공중 부유, 미세 물방울 선명. 고대비 스튜디오 조명+그린 네온 림라이트, 깊은 다크 배경, 광택 알루미늄, 얕은 심도, 포토리얼, 8K, 프리미엄 광고 스타일. ※@iamaiistudio는 aiistudio.com 연계(본문 공개분 수집).",
      "ref_image": null,
      "result": "results/promptlab-2.png",
      "seed": 922705371
    },
    {
      "id": "annisa-1",
      "source": "https://x.com/SimplyAnnisa/status/2071783914595897555",
      "author": "@SimplyAnnisa",
      "date": "2026-06-30",
      "lang": "en",
      "target_model": "GPT IMAGE 2",
      "category": "아트 초상",
      "title": "하드엣지 모던아트 초상 (스크린프린트, 더치앵글 9:16)",
      "prompt": "A striking piece of hard-edge modern art on matte archival paper, with visible screen-printing layers and slight ink misalignment. A young East Asian woman is captured in a sharp, three-quarter profile. Her facial features are rendered with precise, crisp contours, contrasting with abstract, luminous geometric shapes that seem to emanate from within her skin. She wears a sleek, high-collared jacket in deep midnight blue, adorned with a single, bold neon coral brooch in the shape of a sharp triangle. Her dark hair is styled in a severe, architectural bob with blunt edges. Her expression is calm and detached, eyes gazing off-frame. The background is a clean, architectural space with sharp diagonal planes in crisp white and deep slate. High-contrast chiaroscuro lighting highlights the edges of her silhouette. Sophisticated palette: deep midnight blue, crisp white, electric neon coral. A stray cat tail is rendered as a sharp, geometric vector in the bottom left corner. Ultra-modern artistic style. No digital CGI feel. dutch angle, stray cat tail --ar 9:16",
      "gen_prompt": "A striking piece of hard-edge modern art on matte archival paper, with visible screen-printing layers and slight ink misalignment. A young East Asian woman is captured in a sharp, three-quarter profile. Her facial features are rendered with precise, crisp contours, contrasting with abstract, luminous geometric shapes that seem to emanate from within her skin. She wears a sleek, high-collared jacket in deep midnight blue, adorned with a single, bold neon coral brooch in the shape of a sharp triangle. Her dark hair is styled in a severe, architectural bob with blunt edges. Her expression is calm and detached, eyes gazing off-frame. The background is a clean, architectural space with sharp diagonal planes in crisp white and deep slate. High-contrast chiaroscuro lighting highlights the edges of her silhouette. Sophisticated palette: deep midnight blue, crisp white, electric neon coral. A stray cat tail is rendered as a sharp, geometric vector in the bottom left corner. Ultra-modern artistic style. No digital CGI feel. dutch angle, stray cat tail",
      "prompt_ko": "매트 아카이벌 페이퍼 위 하드엣지 모던 아트, 가시적 스크린프린트 레이어+약간의 잉크 어긋남. 젊은 동아시아 여성의 날카로운 3/4 측면. 정밀·선명한 윤곽의 이목구비 vs 피부에서 발산되는 추상 발광 기하 형태. 깊은 미드나잇 블루 하이칼라 재킷+날카로운 삼각형 네온 코랄 브로치. 다크 헤어는 엄격한 건축적 보브(블런트). 차분·초연한 표정, 시선은 프레임 밖. 배경=크리스프 화이트·딥 슬레이트 사선 평면의 건축 공간. 고대비 키아로스쿠로. 팔레트: 미드나잇블루·크리스프화이트·일렉트릭 네온코랄. 좌하단에 길고양이 꼬리를 날카로운 기하 벡터로. 울트라모던, CGI 느낌 금지. 더치앵글. 9:16. ※--ar 제거.",
      "ref_image": null,
      "result": "results/annisa-1.png",
      "seed": 498710025
    },
    {
      "id": "gdgtify-5",
      "source": "https://x.com/Gdgtify/status/2071572895072207185",
      "author": "@Gdgtify",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT/범용",
      "category": "미니어처/그리드",
      "title": "도시=디저트 미니어처 2×2 그리드 (먹을 수 있는 미니도시)",
      "prompt": "16:9 <instructions> Do this for [COUNTRY]. Input: country — analyze the country, its food, its lesser known cities, pick 4 famous cities. A 2x2 grid of 4 famous food or desserts for this country as functioning lesser-known micro-cities [made with popular food and desserts of city 1..4]. Photoreal miniature scenes built into real food or dessert portions, edible details, soft food-styling light, shallow depth of field, centered on white porcelain plinths, 50mm perspective, solid seamless slate-gray background, crisp focus. Name underneath in sugar. </instructions>",
      "prompt_ko": "16:9. [국가]에 대해: 국가·음식·덜 알려진 도시 분석 후 유명 도시 4개 선정. 그 나라 대표 음식/디저트 4개를 '작동하는 미니 도시'로 만든 2×2 그리드(각 도시의 인기 음식·디저트로 제작). 실제 음식/디저트 분량에 지어진 포토리얼 미니어처 장면, 먹을 수 있는 디테일, 부드러운 푸드스타일링 조명, 얕은 심도, 흰 도자기 받침대 중앙, 50mm 원근, 솔리드 심리스 슬레이트그레이 배경, 선명 포커스. 하단에 설탕으로 이름.",
      "ref_image": null,
      "result": "results/gdgtify-5.png",
      "seed": 1876359512
    },
    {
      "id": "prime-1",
      "source": "https://x.com/Prime_54/status/2071582783349428653",
      "author": "@Prime_54",
      "date": "2026-06-29",
      "lang": "en",
      "target_model": "GPT image 2.0",
      "category": "캐릭터 포스터",
      "title": "애니-테크웨어 에디토리얼 포스터 4종 시리즈 (캐릭터 재해석)",
      "prompt": "Create a premium anime-techwear editorial poster series featuring {character_name} from {franchise}, redesigned as a futuristic streetwear icon. Generate 4 completely different vertical poster compositions in one cohesive collection, each representing a different emotional state and cinematic energy.\nSTYLE: High-fashion anime illustration x luxury streetwear campaign x cyber graphic design. Ultra-clean lineart, sharp cel shading, layered textures, bold negative space, modern Japanese poster aesthetics, cinematic framing.\nRULES: vertical poster, 4K; white/off-white minimalist background; strong negative space; signature character color as dominant accent + secondary complementary accent; dynamic geometric composition; crisp directional lighting; graphic poster typography; energy paint strokes & motion graphics; sharp shadows with subtle glow.\nCHARACTER: transform original outfit into modern futuristic techwear while preserving iconic identity — layered jackets, utility straps, tactical sneakers, futuristic fabrics, belts, gloves, oversized silhouettes, cyberpunk detailing, reflective materials.\nPOSTER 01 HEROIC ENERGY: explosive forward action pose, wide dynamic stance, energy bursts diagonal, determined fearless expression, motion streaks + glow.\nPOSTER 02 CALM CONFIDENCE: relaxed standing, hands in pockets, minimal motion, fashion editorial energy, calm confident eyes, elegant geometric framing.\nPOSTER 03 DARK & MYSTERIOUS: low crouched/partially hidden, sharp gaze under shadows, moody deep-contrast lighting, abstract fragmented shapes + black paint textures, subtle signature-color glow.\nPOSTER 04 LEGENDARY FINAL FORM: full cinematic power pose facing viewer, large energy aura, flowing clothing, graphic elements exploding outward.\nBACKGROUND: abstract geometric layouts, layered shapes, subtle grids, paint splashes, futuristic symbols, motion graphics, luxury editorial typography, Japanese visual elements, diagonal flow.\nLIGHTING: hard directional studio + cinematic anime glow, sharp edge highlights, high-contrast shadows.\nRENDERING: extremely polished anime illustration, luxury poster quality, vector-clean with painterly detailing, modern anime-techwear, collectible poster series.",
      "prompt_ko": "{캐릭터}({프랜차이즈})를 미래적 스트리트웨어 아이콘으로 재해석한 프리미엄 애니-테크웨어 에디토리얼 포스터 4종(한 컬렉션, 각각 다른 감정·시네마틱 에너지). 스타일: 하이패션 애니 일러스트×럭셔리 스트리트웨어×사이버 그래픽. 울트라클린 라인아트·샤프 셀셰이딩·볼드 여백·일본 포스터 미학. 공통: 세로 4K·흰/오프화이트 미니멀 배경·강한 여백·캐릭터 시그니처색 주조+보조 보색·다이내믹 기하 구성·그래픽 타이포·에너지 페인트·글로우. 캐릭터: 원본 의상을 미래 테크웨어로(레이어드 재킷·유틸리티 스트랩·택티컬 스니커즈·오버사이즈·사이버펑크). 포스터①영웅에너지(폭발 액션) ②차분한 자신감(편안한 스탠딩) ③다크미스터리(웅크림·그림자 시선) ④레전드 파이널폼(파워 포즈+오라). 배경: 추상 기하·페인트 스플래시·미래 심볼·일본 비주얼. 조명: 하드 디렉셔널+애니 글로우. 렌더: 폴리시드 애니 일러스트·벡터클린+페인터리·수집용 포스터 시리즈.",
      "ref_image": null,
      "result": "results/prime-1.png",
      "seed": 2069370003
    },
    {
      "id": "taaruk-1",
      "source": "https://x.com/Taaruk_/status/2071815503212130407",
      "author": "@Taaruk_",
      "date": "2026-06-30",
      "lang": "en",
      "target_model": "GPT image 2",
      "category": "여행 포스터",
      "title": "빈티지 미니멀 여행 포스터 (지브리·스칸디, 국립공원)",
      "prompt": "Create a premium minimalist vintage travel poster of [LOCATION], inspired by Japanese editorial illustration, Studio Ghibli background art, Scandinavian minimalism, and luxury tourism magazine covers.\nStyle: Soft pastel color palette, flat vector illustration, clean geometric shapes, elegant linework, subtle paper grain texture, muted earth tones, atmospheric depth, soft sunlight, high-end travel brochure aesthetic, calm and peaceful mood.\nComposition: A wide scenic landscape with the destination's most iconic landmark dominating the center. Include a winding road or hiking trail leading into the scene, a parked 4x4 off-road vehicle, hikers with backpacks, photographers, travelers exploring viewpoints, small native plants, desert shrubs, rock formations, layered mountains, soft blue sky with minimal clouds, creating a sense of adventure and scale.\nTypography: Large elegant serif title in the upper-left: \"[DESTINATION NAME]\". Small poetic subtitle underneath: \"[Inspirational travel slogan]\" (e.g. Time carved in stone / Red silence under the sky / Where adventure begins / Nature sculpted by time / Wander beyond the horizon).\nLayout: Vertical A4 poster, large clean negative space, sophisticated editorial typography, modern tourism branding, minimal balanced composition, no logos, no watermark, no unnecessary text.\nArt Direction: Luxury travel poster, premium national park illustration, cinematic perspective, soft atmospheric haze, highly detailed landscape, subtle shadows, clean vector finish, pastel desert palette, award-winning Behance illustration, magazine-quality artwork, ultra-detailed, 8K.",
      "prompt_ko": "[장소]의 프리미엄 미니멀 빈티지 여행 포스터, 일본 에디토리얼 일러스트·지브리 배경아트·스칸디나비아 미니멀리즘·럭셔리 관광 매거진 커버에서 영감. 스타일: 부드러운 파스텔 팔레트·플랫 벡터·깔끔한 기하 형태·우아한 라인워크·미세한 종이 그레인·차분한 어스톤·대기 깊이감·부드러운 햇살·하이엔드 여행 브로셔·평온한 무드. 구성: 목적지 상징 랜드마크가 중앙을 압도하는 와이드 풍경, 굽이진 길/하이킹 트레일, 주차된 4x4 오프로드, 배낭 멘 하이커·사진가·전망 탐험가, 작은 자생식물·사막 관목·암석·레이어드 산·옅은 구름의 파란 하늘 → 모험감·스케일감. 타이포: 좌상단 큰 우아한 세리프 타이틀 \"[목적지명]\" + 아래 짧은 시적 부제(예: Time carved in stone / Where adventure begins). 레이아웃: 세로 A4·넓은 여백·세련된 에디토리얼 타이포·모던 관광 브랜딩·미니멀·로고/워터마크/불필요 텍스트 없음. 아트디렉션: 럭셔리 여행 포스터·국립공원 일러스트·시네마틱 원근·옅은 안개·디테일 풍경·클린 벡터·파스텔 사막 팔레트·Behance·매거진급·8K.",
      "ref_image": null,
      "result": "results/taaruk-1.png",
      "seed": 43432344
    }
  ]
};